### ISSUE TITLE
Improve Card layout in Cohorts page

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#102]
# Summary

Improvement of the Card layout in Cohorts page
# Background

Here is how the layout looks at present -

![Screenshot (87)](https://user-images.githubusercontent.com/85057583/163704196-6088f2e5-48e8-4029-be76-4b312340f526.png)
 
This is the Expected Outcome-

![Screenshot (88)](https://user-images.githubusercontent.com/85057583/163704368-d8a84555-6e80-47a9-a80b-152193c57c5a.png)

Pictures speak more than words! 

**Is the improvement related to a problem? Describe the problem**:
Here the card layout is not symmetric which gives bad User Experience to the User. 

**What does the improvement look like to you?**:
This is just a small change but i think this is something necessary

# Details

We can do it by changing a bit CSS.

# Outcome

This will enhance User Experience in Inventory Site.

**Comment by Neha9849** [comment]
Currently Cohorts partial is not implemented in this Repo. 
We have two options now:

1. Make the Changes in Inventory Repository.
2. Waiting till the issue #35 gets solved to move further.

**Comment by jwflory** [comment]
Thanks for leading on this work @Neha9849, including on porting the layouts into the Inventory theme.
