### ISSUE TITLE
Remove Related Articles section when there are no related articles.

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#104]
# Summary

Remove Related Articles section when there are no related articles.

# Background

Related Articles heading appers even when there is nothing under it.
**Here is an example which shows this problem:**
![Screenshot (92)](https://user-images.githubusercontent.com/85057583/163707655-0ac4fba3-54a7-4f8b-a8eb-e3e4f5a34f06.png)

**Is the improvement related to a problem? Describe the problem**:
A heading without any content under it makes no sense. This leads to confusion among users which ultimately leads to bad User Experience.

# Details

There are two possible ways to solve this problem. They are:

1. Displaying a message something like _Nothing to show_ when there are no related articles.
2.  Conditinally rendering the related article section only when related articles exist.

# Outcome

This improvement leads to a better User Experience.

**Comment by jwflory** [comment]
I'm trying to remember which PR fixed this now 🤔 Guess I forgot to tag it up in this issue.

**Comment by Neha9849** [comment]
Actually, I tried working on this issue and found out that, everything is alright in the actual website.
I think, I found this issue in my local setup and may be it has some extra changes which ended up causing the above mentioned issue.
It was my mistake. I closed it as this issue is irrelevant.
