### ISSUE TITLE
Block Quotes not using text-color-dark

### ISSUE THREAD

**Issue by Nolski** [unicef/inventory-hugo-theme#105]
# Summary

Due to the fact that blockquote contains paragraph tags within them from the markdown parser, the paragraph tag's text color CSS is overwriting that of the block quote and making quote text difficult to read.

# How to reproduce?

1. Create page containing block quote
2. Observe very light colored text in quote

# Expected behavior

Text is color of text_color_dark in configuration file

# Actual behavior

Text is color of text_color in configuration file

**Screenshots**:

![screenshot_2022-04-19-083618](https://user-images.githubusercontent.com/2600677/163950477-26c11943-b44a-4f8d-80ed-2458cf76df4e.png)

# Other details

**Comment by jwflory** [comment]
Thanks for your PR on this one @Nolski! We're coming out of the Outreachy community contribution phase and hope to review your PR soon.
