### ISSUE TITLE
As a reader, I want simple navigation of all pages in a top-level category so that I can quickly see other topics and navigate to other pages if desired.

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#122]
### Summary

The sidebar is the relevant component of this user story. The main issue is the sidebar is not responsive. On mobile devices, the sidebar is moved to the top of the page. In categories with a lot of content, this makes the reader do a lot of scrolling to get to the content.

There are possibly other improvements to make to the sidebar on larger viewports too.

### Priority

primary

### Category

front-end

### Type

functional

**Comment by jwflory** [comment]
@Neha9849 Per the sprint retrospective today, I am tagging this issue for Sprint 2 from 13–24 June.

**Comment by Neha9849** [comment]
@jwflory here is my first mockup, I will design a few more and than we can see which looks better.
![Desktop - 1](https://user-images.githubusercontent.com/85057583/173689426-176a5c6d-d7a0-49a4-a47f-ad909452f4e9.png)

**Comment by jwflory** [comment]
Hey @Neha9849, as we discussed today, this desktop view looks like a good start. I am also keen to see the mobile view though since that view does not exist in the theme presently.

I like the idea of merging the breadcrumbs into the topmost navigation bar and making the sidebar more visually distinct by using the full vertical space. This reminded me of another design from a documentation site that I liked:

[![Screenshot of a Fedora Linux documentation page, demonstrated a sidebar with cues for where the reader is inside the article.](https://user-images.githubusercontent.com/4721034/173978108-9179f588-52e4-49cb-ad81-d622de74d1bb.png)](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/#sect-relabel-files-with-the-latest-selinux-policy "Screenshot of a Fedora Linux documentation page, demonstrated a sidebar with cues for where the reader is inside the article.")

Note the visual cue in the sidebar that indicates where the reader is in the page. This page can be found [here](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/#sect-relabel-files-with-the-latest-selinux-policy). An example of this interface can be found [here](https://fedora.gitlab.io/docs/docs-website/ui-bundle/). Its source code is also open source [on GitLab](https://gitlab.com/fedora/docs/docs-website/ui-bundle) under the [Mozilla Public License 2.0](https://gitlab.com/fedora/docs/docs-website/ui-bundle/-/blob/main/LICENSE) (the same license [as our project](https://github.com/unicef/inventory-hugo-theme/blob/main/LICENSE.txt)). We could borrow code from that interface but we must cite our sources properly in the README if we borrow any code.

**Comment by Neha9849** [comment]
@jwflory, here is the mobile mockup

![mobile](https://user-images.githubusercontent.com/85057583/174104238-1e55db17-0ef7-46f3-a2cc-c65fc388773a.png)

**Comment by Neha9849** [comment]
In this mockup, there are two menu icons and this kinda looks weird🤔

**Comment by Neha9849** [comment]
![mobile2](https://user-images.githubusercontent.com/85057583/174105134-35f6a48d-80e3-4cf9-bee0-94167a3cb431.png)
Here, i have made a slight modification.

**Comment by Neha9849** [comment]
> Note the visual cue in the sidebar that indicates where the reader is in the page. This page can be found [here](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/#sect-relabel-files-with-the-latest-selinux-policy). An example of this interface can be found [here](https://fedora.gitlab.io/docs/docs-website/ui-bundle/). Its source code is also open source [on GitLab](https://gitlab.com/fedora/docs/docs-website/ui-bundle) under the [Mozilla Public License 2.0](https://gitlab.com/fedora/docs/docs-website/ui-bundle/-/blob/main/LICENSE) (the same license [as our project](https://github.com/unicef/inventory-hugo-theme/blob/main/LICENSE.txt)). We could borrow code from that interface but we must cite our sources properly in the README if we borrow any code.

I think, our case is slightly different. if we incorporate the breadcrumbs in the top than we will have two navigation bars.
Are, you suggesting to keep the sidebar to the left in place of contents?

**Comment by Neha9849** [comment]
![2nd](https://user-images.githubusercontent.com/85057583/174118327-b495aef8-f72b-44ca-90e3-abd73eae99d9.png)

**Comment by Neha9849** [comment]
![3rd desk](https://user-images.githubusercontent.com/85057583/174121416-fe7d10be-6813-434d-b66a-a5b7422cf278.png)

**Comment by jwflory** [comment]
@Neha9849 What is the status update here?
