### ISSUE TITLE
As a prospective DPG applicant, I want fast and quick information about the DPG Standard so that I can understand what might be required of my project.

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#126]
### Summary

This is one of two key user stories for the Outreachy 2022 internship.

This user story is focused on **content**. The existing content in the UNICEF Open Source Inventory site is related to the Digital Public Goods Standard, but it is ordered in its own categories. There is no demonstrated connection between the existing content and the DPG Standard. The content will need to be reorganized in a new way to better connect to the DPG Standard.

One straightforward approach is to change the category system in `unicef/inventory` to categories for each DPG Standard indicator, and moving existing content from the old categories into the DPG categories.

### Priority

primary

### Category

design

### Type

business

**Comment by jwflory** [comment]
@Neha9849 Per our sprint retrospective today, I am tagging this Issue for Weeks 3-4 to track user interviews with our three key stakeholder groups. We can use the comments in this Issue to document feedback we collect from user stories.

1. [UNICEF Venture Fund](https://www.unicefinnovationfund.org/) team (a mostly non-software team)
2. UNICEF open source developers (mix of software and non-software teams)
3. Start-up companies supported by UNICEF Venture Fund (many software teams)

You can share your outline and any research notes as comments in this Issue. We'll look at your outline and research together on Wednesday (15 June).

**Comment by Neha9849** [comment]
@jwflory Can you give more insights on this :)

**Comment by jwflory** [comment]
@Neha9849 Recapping our discussion on the [user interview outline](https://docs.google.com/document/d/1K9VVI-MDbbD78jTzbXnYa7hQOCP6Tvvg8c-n5KMv59Q/edit?usp=sharing) in stand-up today:

1. This issue (#126) is focused on content organization and structure. The current thinking is to restructure the existing categories (e.g. _Documentation_, _Governance_, _Legal & Policy_, etc.) into categories for the DPG Standard indicators (e.g. _1. Relevance to SDGs_, _2. Open Licenses_, etc.).
2. Issue #128 focuses on content and design, specifically tying in the DPG Help Center documentation and creating a custom layout for the index pages to act as a "spotlight" for each DPG Standard indicator.

The outcomes for both #126 and #128 are contingent on the user interviews and what we learn by talking to each stakeholder group. As we speak to more users, the direction will become more clear. We will check in with Prateek on Wednesday to review the current draft, and then start scheduling interviews for the following week.

Let me know if you have any doubts!

**Comment by jwflory** [comment]
Today, @Neha9849 and I met with Prateek in the Office of Innovation to go over user testing, interviews, and brainstorming on the best approach to tackle this. Our approach will change slightly based on this feedback:

1. Next sprint (27 June to 8 July): **Restructure the existing content in the Open Source Inventory around the DPG Standard**. This will become the prototype we share during user interviews to evaluate whether we are on the right track.
2. By this Friday (24 June): Add learning goals, statement of interview purpose, and email introduction text to the existing outline.

We will start scheduling interviews early next week with the email text so we have enough time for interviewees to prepare and accept the invitation. @Neha9849, I will ask you to send these email invites next week to the UNICEF start-up teams and the Venture Fund team.

**Comment by jwflory** [comment]
Here is a quick recap and notes of today's weekly stand-up call.

## DPG Standard walkthrough

We reviewed the DPG Standard and the indicators, what each one means, and how the Open Source Inventory and other mentor toolkits will cover guidance about the DPG Standard.

## Existing Inventory pages

- **Communities**: Move into DPG#8 as real-world examples.
- [**Developer Tools & Automation**](https://unicef.github.io/inventory/dev-tools/): Move and redirect to @iperdomo's Software Development Toolkit (see [existing CI page](https://github.com/unicef/ooi-toolkit-software/blob/main/content/technical-capabilities/continuous-integration.en.adoc) in SD Toolkit)
- **Documentation**: Move to DPG#5
- **Governance**: Move to DPG#3
- **Legal & Policy**: Move to DPG#2
- **Meta**:
    - Open Source Inventory: Move to theme website as documentation
    - Open Source Mentorship: Keep under _Resources & Practices_, but may move somewhere else depending on user testing feedback (including _[Workflow: Update external UNICEF metrics](https://unicef.github.io/inventory/meta/workflow-metrics/)_)
- **Missions**: Get rid of the category, but we may want a special button/layout for highlighting DPG indicators that _do_ have missions (especially using the [template](https://raw.githubusercontent.com/unicef/inventory/main/content/missions/_template.en.adoc))
    - Charters: Move to DPG#3
    - Codes of Conduct: Move to DPG#9c
    - Good first issues: Move to DPG#8
- **Open Hardware**: Move to DPG#8
- **Project management**: Move to DPG#8
- **Reproducibility/Reproducibility reading list**: Move to @dalvarez83's Data Science & A.I. Toolkit
- **Sustainability/Open-first business practices**: Move to DPG#3

## Remaining DPG indicators

- DPG#1: Redirect to UN SDGs site
- DPG#4: Redirect to @iperdomo's _Platform Independence_ category in the Software Dev Toolkit
- DPG#6: Check-in with @iperdomo on whether this should go into the Software Dev Toolkit
- DPG#7: Get introduced to Lydia, the new Data Privacy & Security Mentor, about whether she will publish a new toolkit, or whether she wants to publish content here
- DPG#9: During user testing, get a better understanding for challenges/concerns with _Do No Harm_ and identify new content that could help solve challenges.

**Comment by jwflory** [comment]
Here is the text we can use for the category descriptions that appear on the home page:

* **DPG Indicators**: Detailed information and guidance on the indicators of the DPG Standard and how to achieve them in an open source work.
* **Open Source Resources & Best Practices**: Miscellaneous guidance, resources, and best practices around creating, maintaining, and participating in an open source community.

**Comment by jwflory** [comment]
In Sprint 5 (ending today), we began the user testing interviews and got to know the real experiences of Venture Fund team members and UNICEF Venture Fund start-up companies using the Open Source Inventory. This feedback now exists in a confidential notes sheet from each interview we conducted.

Now, we need to organize the feedback and open new user stories based on the feedback we collected. The new user stories will either be sorted into the backlog as "open for contribution" or we will prioritize them in Sprint 6 and Sprint 7.

**Action points**:

- @Neha9849: Organize the (private) interview notes and group feedback collected by component (i.e. which part of the website their feedback was about).
- @jwflory: Create new (public) user stories based on the grouped feedback and triage in the project board.

**Comment by Neha9849** [comment]
@jwflory 
What else is to be done to close this issue?

**Comment by jwflory** [comment]
@Neha9849 Once the user feedback from the interviews is organized and grouped, I will open new user stories from the feedback. We can group some of those user stories as sub-tasks of this issue, and close this one once they are complete.

**Comment by jwflory** [comment]
Fixed in unicef/inventory#136.
