### ISSUE TITLE
As a contributor, I want a definition of key stakeholders so that I can understand who the users are and what their needs might be.

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#127]
### Summary

Related to #89.

Three stakeholder groups:

1. [UNICEF Venture Fund](https://www.unicefinnovationfund.org/) team (a mostly non-software team)
2. UNICEF open source developers (mix of software and non-software teams)
3. Start-up companies supported by UNICEF Venture Fund (many software teams)

### Priority

primary

### Category

documentation

### Type

business

**Comment by Neha9849** [comment]
@jwflory where we are supposed to add this in the documentation?

**Comment by jwflory** [comment]
@Neha9849 A page about the key stakeholders makes up a new "Contributing" section in the example documentation site, which will capture more details about contributing to the UNICEF Inventory site and the UNICEF Toolkits using it (#89). It will become more clear where things like this belong in the coming weeks as #89 progresses.
