### ISSUE TITLE
Show an author byline when author attribute entry is specified

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#15]
# Summary

Add a byline with author names and emails (if provided) when `:author:` attribute entry is used

# Background

**Is your improvement related to a problem? Please describe**:

Some articles are written by guest experts or external folks from the UNICEF Office of Innovation. It would be good to accent that visually from the body of the article content when an author is provided.

**Describe the solution you'd like**:

A single common way across all pages to show author bylines when they are given.

**Describe alternatives you've considered**:

Today, if we want to highlight an author of a page, it has to be manually typed in. This can vary among writers depending where in the page it is written, in what size and formatting, etc.

# Details

We can use [author attribute entries](https://docs.asciidoctor.org/asciidoc/latest/document/author-attribute-entries/) for specifying this information in a document. We add it to a document like we do with the `:toc:` attribute to show the automated table-of-contents. If a `:author:` attribute entry is provided, it should be given special weight in the HTML document, likely connected near or alongside the page title `<h1>`.

# Outcome

1. Standardize how bylines are shown in the theme
2. Build habit of crediting authors and collaborators who contribute content to this repository

**Comment by jwflory** [comment]
Issue transferred from `unicef/inventory#60` to unicef/inventory-hugo-theme#15.

**Comment by Yavnikaa** [comment]
May I work on this?

**Comment by jwflory** [comment]
Hey @Yavnikaa, you can work on #16 first. If no one else claims this issue before then, let's follow up again after #16.

**Comment by barcha47** [comment]
Hey @jwflory , i have completed my initial 3 tasks. May i work on this or am i eligible to work on this?

**Comment by roli25** [comment]
@jwflory Can I work on this, if still available?

**Comment by chaitri19** [comment]
@jwflory Can I work on this issue if it is not assigned to anybody?

**Comment by yokwejuste** [comment]
hey! greetings @jwflory can I work on this issue for now?

**Comment by jwflory** [comment]
Hi all, thanks for your patience with a reply here.

@roli25, would you still like to take this issue up? You are first in the queue to take it. If so, let me know and I will assign it. If not, I'll open it for the next person to work on.

**Comment by barcha47** [comment]
@jwflory if no one to take this issue, kindly assign it to me.

**Comment by manasvvi1** [comment]
Hey @jwflory,
If this issue hasn't been assigned to anyone yet, can i work on it as a part of the outreachy application process?
Thanks

**Comment by jwflory** [comment]
@roli25 or @chaitri19, would either of you still like to take this issue up? Otherwise, I will open it up for others on Monday, 11 April.

**Comment by chaitri19** [comment]
I would like to work on this issue.
