### ISSUE TITLE
As a reader, I want a better background image in homepage so that I understand the purpose of the site.

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#153]
### Summary

User review from testing:

- Background image on site is misleading; creates slight confusion (e.g. open roles, open positions?). Contrast is difficult.

- Replace background image with something more human and inviting. Connecting to UNICEF mission.

### Priority

primary

### Category

front-end

### Type

functional

**Comment by jwflory** [comment]
Free and open source images we can use for replacing the background image: https://unsplash.com/

**Comment by jwflory** [comment]
Fixed by unicef/inventory#138.
