### ISSUE TITLE
As a reader, I want "Pages" and "Cohorts" dropdown to be more meaningful so that I understand what they mean.

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#155]
### Summary

User reviews in testing:
- “Pages” tab is unclear and not meaningful.
- Confusion about the Pages dropdown
- “Pages” drop-down is not clear. What does it mean?

### Priority

primary

### Category

front-end

### Type

functional

**Comment by jwflory** [comment]
Change "Cohorts" to "DPG Projects" or similar.

**Comment by Neha9849** [comment]
@jwflory what should i change cohorts into

**Comment by jwflory** [comment]
`DPG Projects` is sufficient for now.
