### ISSUE TITLE
As a reader, I don't want to redirect to new website on clicking toolkits.

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#156]
### Summary

User reviews in testing:

- Toolkits navigation was confusing; disruptive to change to new site
- What are toolkits? Some sites have different content. Unclear that there are different websites.

### Priority

primary

### Category

design

### Type

functional

**Comment by jwflory** [comment]
Move from top navigation into a new card in the home page. Using the existing default layout, this new category only has an index page that describes the other toolkits and where to find them. No new layout needed.

**Comment by Neha9849** [comment]
@jwflory I should be working on staging the repo for this right?

**Comment by jwflory** [comment]
@Neha9849 Right.

**Comment by Neha9849** [comment]
@jwflory This issue has been covered in inventory-staging

**Comment by jwflory** [comment]
Acknowledged. Next, you need to update PR unicef/inventory#136 and rebase it on latest `main` to prep it for a final review and merge.

**Comment by jwflory** [comment]
Fixed in unicef/inventory#136.
