### ISSUE TITLE
As a reader, I want to go the home page on clicking on the unicef logo.

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#157]
### Summary

User reviews in testing:

- Clicking UNICEF logo takes you to UNICEF website; clicking on either should go to the same page (i.e. O.S. Inventory)
- UNICEF.org redirect from top logo was confusing!

### Priority

primary

### Category

front-end

### Type

functional

**Comment by jwflory** [comment]
Remove the `<a>` attribute from the logo so it is no longer clickable.
