### ISSUE TITLE
Create more appealing and responsive table of contents

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#16]
# Summary

The table of contents, when specified (#29 / unicef/inventory#58), is not responsive and is somewhat visually confusing; design and implement a more modern and responsive table of contents.

# Background

**Is your feature request related to a problem? Please describe**:

The current table of contents is not visually distinct in the article. "Table of Contents" string is isolated and not visually connected to the actual ordered list. White space between TOC entries is not consistent and visually confusing. It is not visually clear where the TOC begins, where it ends, and when the article content begins.

![image](https://user-images.githubusercontent.com/4721034/130117756-889608b7-15a3-4863-9520-cb7d5b47aaf1.png)

The TOC is not responsive and takes a lot of screen space on mobile devices.

![Screenshot of a page in the design of an Android Galaxy phone. The table of contents takes up the majority of the screen space.](https://user-images.githubusercontent.com/4721034/130118235-02d04a99-db6d-49a3-b654-29e5abc1a593.png)

**Describe the solution you'd like**:

Something more visually distinct, modern, and responsive for mobile devices.

**Describe alternatives you've considered**:

None. Hugo does make this easier with templates.

# Details

There are two steps to complete this issue:

1. Design a pseudo version in the browser editing tools and share a screen shot here for review
2. Update the [Table of Contents template](https://gohugo.io/content-management/toc/#template-example-toc-partial) for the theme to implement the pseudo version in the theme.

Since this one is more complex, it is better we start with a specific design task on this one. The easiest way to test this out is to navigate to the [existing Inventory](https://unicef.github.io/inventory/) and use the browser tools to edit the live HTML. For example, Firefox allows this with its Developer Tools. It is also possible to test out viewports from smaller screen sizes with Firefox Developer Tools.

Once we review and agree on a design, then we can jump into the software implementation in the theme. It may be something we want to upstream too.

# Outcome

More visually-appearing Table of Contents that reflects modern web design practices

**Comment by jwflory** [comment]
Issue transferred from `unicef/inventory#61` to unicef/inventory-hugo-theme#16.

**Comment by Idadelveloper** [comment]
Hi @jwflory. I did a little bit of tweaking with my browser dev tools and please tell me what you think:

![toc-1](https://user-images.githubusercontent.com/56026636/157024262-7e5652f2-fdcb-4590-bb2c-8c81b247a751.png)
![toc-2](https://user-images.githubusercontent.com/56026636/157024284-0ebc98e6-ee09-4bce-ada4-253e028be5e1.png)

What do you think should be added or changed?

**Comment by jwflory** [comment]
@Idadelveloper Looking good! The contrast and title heading for _Table of Contents_ look nice. I have two suggestions to improve it:

1. Adding a border to the box would be nice, similar to how [Wikipedia articles](https://en.wikipedia.org/wiki/Nowruz) do it. It would make the contrast more distinct.
2. Removing the bullet points from the unordered list would be nice. I think the bullets are unnecessary since the table of contents is already numbered.

**Comment by jwflory** [comment]
@Idadelveloper Should I go ahead and assign this issue to you if you are working on it? Since the next Outreachy round is coming up, it would be a good idea to assign it if you are, so someone else doesn't duplicate the same work twice.

**Comment by Idadelveloper** [comment]
Oh. @jwflory I might be a little slow with the issue. Also, this is a really good issue for the next intern 😏.
Is it possible for me to be an outreachy mentor for the inventory? Or must I be a UNICEF employee?  I'll really love to help with this since I'm familiar with the repo.

**Comment by jwflory** [comment]
@Idadelveloper For sure! It would be great to have you on board as a mentor. 🚀 Are you able to join our [Matrix room](https://matrix.to/#/#unicef-innovation:matrix.org)? This is where I am coordinating with applicants once they start rolling in. Feel free to drop an intro in the channel and say hi once you're there! If you never used Matrix before, you can see the [getting started page](https://element.io/get-started) for the Element chat client.

**Comment by Yavnikaa** [comment]
Hey, is there already work going on this? Or shall I get on it?

**Comment by jwflory** [comment]
Hey @Yavnikaa, you can take this one and @Idadelveloper can review your Pull Request when ready. I'll assign this one to you.

Go ahead and use the mockup posted by Ida above, and you can incorporate my feedback into it. When you're ready, you can open a pull request for review. If you have any questions while working on this, ask away here or in the Matrix room.

**Comment by Yavnikaa** [comment]
Sure! I totally agree with your feedback and would incorporate it.
Also, I was thinking that to reduce the space it takes up, do we add a dropdown or rather accordion like feature, to the parent headings. Like, across the 1.0 point we can have an arrow. If the arrow is downside, that means we can click it and reveal with the children components like 1.1, 1.2 here and the arrow turns upwards. This can help us save some space and will be less-distracting. What do you think?

**Comment by jwflory** [comment]
@Yavnikaa I like the idea of using an accordion. I am keen to see an early prototype/mockup to visualize your idea. Could you share a mockup preview and upload it as an image to this issue? If we are aligned on its design, then you can put the code together for it.

**Comment by Yavnikaa** [comment]
![image](https://user-images.githubusercontent.com/56485761/158246029-e9c8571d-29d7-42ed-8ad6-e5791f9d8427.png)

This is what I have been thinking. Does this look fine? Looking forward to the feedback ^.^

Also, I was browsing through the code and as per what I understand, I to edit the toc there must be a file within `layouts/partials/` , by the name of toc.html but I couldn't find one. So, could you please help me navigate what part of code are we supposed to make changes on, of course after the design is discussed and finalised.

![Screenshot (212)](https://user-images.githubusercontent.com/56485761/158246670-b6de445a-a63d-4af8-9c85-9a829e8dfd4f.png)

**Comment by Yavnikaa** [comment]
Yes, you are right about opening the first on default in large width devices, and keeping it closed on mobile screens. Thankyou for approving the design so quickly! :)

Also, though I got the concept that we have kept preserveTOC as true in our website and hence `asciidoctor` is handling on its own, but I'm still confused about where do the css classes come from? As far as I could figure out, it is maybe linked to `docs/_vendor/github.com/gohugoio/gohugoioTheme/assets/css/_hugo-internal-template-styling.css`. Can you please help me with this? Sorry to ask such basic doubts

**Comment by Yavnikaa** [comment]
Ahh, alright, Seems quite interesting!
Now I can appreciate the structure and the flow clearly and it makes sense to me that modifying the existing structure of TOC. So, I think its [this file](https://github.com/asciidoctor/asciidoctor/blob/main/src/stylesheets/asciidoctor.css) which needs to be worked upon. I hope I have got it right this time.
But here, I have a small doubt. The accordion would require some js to be written. So how and where do I add my js file? If it's much of a hassle, I'll read up and maybe do something for the accordion using advanced CSS. I think we can workaround here, just need a little guidance from you on this once, so putting it here!

**Comment by jwflory** [comment]
> **_@Yavnikaa wrote…_**
> So, I think its [this file](https://github.com/asciidoctor/asciidoctor/blob/main/src/stylesheets/asciidoctor.css) which needs to be worked upon. I hope I have got it right this time.

Not quite. The CSS needs to be defined in the site CSS stylesheet, see [here](https://github.com/unicef/inventory-hugo-theme/blob/main/assets/css/style.css). This is the custom stylesheet we use. You can add styles for the given CSS classes there.

> **_@Yavnikaa wrote…_**
> But here, I have a small doubt. The accordion would require some js to be written. So how and where do I add my js file? If it's much of a hassle, I'll read up and maybe do something for the accordion using advanced CSS. I think we can workaround here, just need a little guidance from you on this once, so putting it here!

Ah, I understand why you ask now. No, it will not be easy to add JavaScript in. The closest you can get to modifying this is wrapping around the `.Content` object output in the layout, see [here](https://github.com/unicef/inventory-hugo-theme/blob/main/layouts/partials/default.html#L27-L28).

To help understand how Hugo looks these things up… for content pages, Hugo looks to the [`layouts/_default/single.html`](https://github.com/unicef/inventory-hugo-theme/blob/main/layouts/_default/single.html) template. The template calls a partial, [`layouts/partials/default.html`](https://github.com/unicef/inventory-hugo-theme/blob/main/layouts/partials/default.html), which is the actual implementation for what you see on an article page. The section I linked above is the part of the default partial where the `asciidoctor`-generated HTML is embedded into the Hugo theme layout.

Does this make sense? Ultimately, the option with the least maintenance friction is CSS only.

**Comment by Yavnikaa** [comment]
Ahh, thanks for helping me understand.
I'll do the needful and raise the PR by EOD! :))

**Comment by jwflory** [comment]
Thanks @Yavnikaa! I will work on reviewing your PR today.
