### ISSUE TITLE
As an open source developer, I want the Resources category to be more specific so that I can quickly find the content I need.

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#161]
### Summary

User reviews in testing:
- “Resources” seems unclear; many people look here first for more information (e.g. licenses)
- Purpose of Resources page was unclear.

### Priority

primary

### Category

front-end

### Type

functional

**Comment by jwflory** [comment]
Rename category to "UNICEF Mentoring"

**Comment by Neha9849** [comment]
@jwflory 
I have done this change in the staging repo and pushed it.

**Comment by jwflory** [comment]
@Neha9849 Thanks for updating! It will also help if you tag issue numbers in your commits, e.g. `Fixes unicef/inventory-hugo-theme#161`.

**Comment by Neha9849** [comment]
@jwflory I think this should be closed as it's already fixed

**Comment by jwflory** [comment]
We'll close when unicef/inventory#136 is merged.

**Comment by jwflory** [comment]
Completed by unicef/inventory#136. Closing as complete! 🎬
