### ISSUE TITLE
Improve user experience of sidebar navigation

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#27]
# Summary

Simplify design of the the sidebar navigation to improve user experience for someone browsing the site.

# Background

**Is the improvement related to a problem? Describe the problem**:

* **Categories with many articles**: When a category begins to accumulate a lot of content (like the [Meta category](https://unicef.github.io/inventory/meta/), the sidebar navigation starts to look busy. It is also not mobile-friendly.
* **Team profiles** (related to #13): Multiple cohorts will include profiles of five to ten teams, which will make the sidebar navigation extend far below the content of the page.

**What does the improvement look like to you?**: The leading idea was to use drop-down menus for sub-sections with many articles, perhaps over a maximum of five?

![Wireframe example of sidebar navigation with a drop-down menu](https://user-images.githubusercontent.com/4721034/137864136-a09e94d7-f87c-45ae-90b4-b7e2abe2e51f.png "Wireframe example of sidebar navigation with a drop-down menu")

**Describe any alternatives considered**: This could be condensed in another way without drop-downs, but for the team profiles feature, this is likely to get very long:

![Wireframe example of sidebar navigation with 'read more' style when the pages in a sub-section exceed a specific count](https://user-images.githubusercontent.com/4721034/137864325-13bcb41c-b4a8-497e-a8a1-b0583ba0d663.png "Wireframe example of sidebar navigation with 'read more' style when the pages in a sub-section exceed a specific count")

# Details

There are two pieces to consider before starting on an implementation.

* **Templating**: What is the best way to check if a drop-down menu should be used (i.e. if there are >5 articles), or if the pages should be displayed without a drop-down menu?
* **Front-end**: What is a user-friendly way to implement drop-downs that looks nice both on desktop and mobile views?

# Outcome

Easier to navigate and browse the Inventory, especially for categories with multiple sub-sections with multiple articles/pages in each sub-section

**Comment by jwflory** [comment]
Reposting this comment from #37:

---

A couple of thoughts for this task:

1. Instead of removing the sidebar, we should either use a more responsive layout, or make them collapsible once they get past a certain count.
1. This change should be made for the sidebar for all pages instead of only the cohorts section.

Instead of removing the sub-sections, I think we should keep them there for navigation. But when the list gets long, we should definitely make some kind of improvement there so it doesn't fill the whole page. This is an issue that also happens when browsing other sections of the site, like the meta category:

https://unicef.github.io/inventory/meta/

I see two possible approaches for improving this with Bootstrap components:

1. [**Collapse component**](https://getbootstrap.com/docs/4.1/components/collapse/): Make sections collapsible once they reach a certain length, e.g. >5 sub-sections.
1. [**Responsive navbar component**](https://getbootstrap.com/docs/4.1/components/navbar/#responsive-behaviors): Convert the sidebar to a Bootstrap navbar, and make it responsive by default with a toggler.

_Edit_: Here is an [example](https://gitlab.com/jwflory/jwflory.gitlab.io/-/blob/main/themes/toph/layouts/partials/nav.html) of a responsive navbar with a toggler. This is done with Bootstrap 5 though, it may be slightly different in Bootstrap 4.

**Comment by jwflory** [comment]
@Idadelveloper Please post the Figma screenshot here of the wireframe we talked about in stand-up when you have a moment.

**Comment by Idadelveloper** [comment]
Here are the proposed designs...

Here's the default menU:
![menu-default](https://user-images.githubusercontent.com/56026636/145767120-ff99045c-e5c0-4fb4-b61b-0dc4488a029b.png)

Here's the menu expanded:
![menu-expanded](https://user-images.githubusercontent.com/56026636/145767253-b86019d6-e5e5-42f3-be06-4598b4a5d28a.png)

**Comment by jwflory** [comment]
In stand-up today, we checked in for the new sprint beginning today. @Idadelveloper is working through the theme on figuring out the best way to construct the sidebar to match the wireframe above.
