### ISSUE TITLE
Hide sub-categories from index page categories

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#32]
# Summary

If a section has sub-categories with index pages, do not show them by default on the index page

# How to reproduce?

1. Create a sub-category (e.g. `mkdir content/legal-policy/licenses/`)
2. Add an index page to the sub-category (e.g. `content/legal-policy/licenses/_index.en.adoc`)
3. View the site index page and see the category shown

# Expected behavior

![Screenshot of the site index page, where only main categories defined in `content/` are shown.](https://user-images.githubusercontent.com/4721034/142603970-b0070628-c10c-4c7d-8af8-0736ea7b84f8.png "Screenshot of the site index page, where only main categories defined in `content/` are shown.")

# Actual behavior

![Screenshot of the site index page, where main categories and sub-categories are shown.](https://user-images.githubusercontent.com/4721034/142603799-ec7ff3d4-5142-4b9e-9331-317c0d4963f5.png "Screenshot of the site index page, where main categories and sub-categories are shown.")

# Other details

It would be good to come up with a way where a sub-category could be shown on the index page, but this should not be the default behavior. It should be "opt-in" to show a sub-category on the index page.

**Comment by jwflory** [comment]
This issue will be solved by the new sidebar design in #45. In the new design, the need to have an index page defining a category and listing the pages within is not as necessary. We can simply remove the index pages from the sub-categories, and they will no longer appear on the index page.

I moved this issue to the "waiting on external" column on the sprint board (blocked until #45 merges).

**Comment by Idadelveloper** [comment]
Hey @jwflory . If you don't want a sub-category or category to be displayed on the index page I think in the front matter you do not specify `type: docs`

Or am I missing the point?

**Comment by jwflory** [comment]
@Idadelveloper No, it really was that easy this whole time. 😀 I opened unicef/inventory#112 to fix this in the short-term, which will close this issue once merged.
