### ISSUE TITLE
Support embedded PDFs in an article

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#33]
# Summary

Embed a PDF document into an article.

# Background

**Is the new feature related to a problem? Describe the problem**:

Sometimes it is desired to render a PDF document on a page. This can be the main deliverable for a page. The user could click to open a link or button, but it is a better user experience to render the PDF inside a page.

**What does the new feature look like to you?**:

Ideally this is accomplished with a Hugo shortcode, so it can be reused and recycled across many pages. As an example:

`{{< pdf "https://example.com/link/to/document.pdf" >}}`

**Describe any alternatives considered**:

Hard-coding HTML is an option but comes at a higher maintainability cost. More duplicate code needs to be maintained in multiple places.

# Details

There are two paths:

1. Explore existing open source options (e.g.[**hugo-embed-pdf-shortcode**](https://github.com/anvithks/hugo-embed-pdf-shortcode))
2. Create our own shortcode and maintain it in the theme

Using an existing open source implementation would be ideal to lower the maintainer cost in this repository. If we needed to fork in a hypothetical future, we always could.

# Outcome

PDFs can be rendered inside a document in correct proportions to the canvas/screen size, with other media options shown

**Comment by Neha9849** [comment]
I think using an iframe something like 
```html
<iframe src="http://docs.google.com/gview?url=http://www.africau.edu/images/default/sample.pdf&embedded=true" style="width:90%; height:700px;" frameborder="0"></iframe> 
``` 
may work without using any library.

Preview:
![Screenshot (21)](https://user-images.githubusercontent.com/85057583/155034223-ece026b0-6b00-4fdc-b501-67ae57085e1a.png)

We can also use <embed> tag

**Comment by jwflory** [comment]
@Neha9849 It is a nice idea, but generally I try to avoid iframes. Some of the drawbacks are explained in [this post](https://www.ostraining.com/blog/webdesign/against-using-iframes/), most notably the challenges with mobile/responsive layouts.

I am open to trying other ideas, but the biggest win we want is getting a [Hugo shortcode](https://gohugo.io/extras/shortcodes/) out of this. Perhaps the easiest approach is using [anvithks/hugo-embed-pdf-shortcode](https://github.com/anvithks/hugo-embed-pdf-shortcode), but I haven't tested it yet to see how compatible it is with the UNICEF Inventory Theme. If it works nicely, we could avoid reinventing the wheel and use someone else's existing work.

**Comment by Neha9849** [comment]
I tried using [anvithks/hugo-embed-pdf-shortcode](https://github.com/anvithks/hugo-embed-pdf-shortcode). But it was not working for me. Can you test it once ?
