### ISSUE TITLE
Add "edit this page" banner to view source content of a page in GitHub

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#50]
# Summary

Add a banner, button, or something else distinct titled "edit this page", which when clicked, takes the user to the source material in the source forge of choice (e.g. an AsciiDoc page on GitHub.com).

# Background

**Is the new feature related to a problem? Describe the problem**: All the content on the site is open source, but it is not clear or intuitive that edits are welcome or accepted. A call-out makes it easier to attract casual contributors by people flying by the website.

**What does the new feature look like to you?**: This banner or button should appear near the top and bottom of a page. It could also be fixed in the viewport as the user scrolls, but this needs careful consideration for mobile. More design thinking could be done on how best to design this feature. 

**Describe any alternatives considered**: We can always manually link the source material in a page, but this runs a high risk of becoming outdated if the page title or URL ever changes. Something automated is best so it will keep up with the document metadata instead of requiring an editor to manually fix a link.

# Details

I learned about the possibility to do this while reading the [Hugo v0.92.0 changelog](https://github.com/gohugoio/hugo/releases/tag/v0.92.0), which talks about `.Path` and how this is changing to a canonical content path in Hugo v0.93. So, given the functionality is there and all of the content is public here on GitHub, we should make it easier for contributions to happen.

This might require a new config value, maybe `edit-prefix` which would look something like `https://github.com/unicef/inventory/tree/main/content`. Pseudo code below:

```html
<a href="{{ $.site.params.edit-prefix }}/{{ .Path }}">edit this page</a>
```

# Outcome

Encourage contributions to content source material

**Comment by Neha9849** [comment]
That sound's great! I would like to contribute.

**Comment by jwflory** [comment]
Hey @Neha9849, thanks for your interest in working on this! 🙌🏻 I would be happy to review a PR from you for this issue. I think a good place to start would be a mock-up or preview of what this might look like first, before writing code. Perhaps a button in the top of the page could be best, but curious to see what you come up with.

Do you need any guidance from me on getting started? Let me know how I can help you be successful in working on this. 🚀

**Comment by Neha9849** [comment]
Hey @jwflory , I am currently working on hugo, as i am new to this. I will be asking you if i have any issue. And i thought of a button in the Navbar.  Something like this-
![Screenshot (7)](https://user-images.githubusercontent.com/85057583/153271548-7cc36076-2848-450e-9eb8-f2827398b3e8.png)
Do this community have any channels for diccussions? Lemme me know if there is one :)

**Comment by jwflory** [comment]
> _**@Neha9849 wrote…**_
> Hey @jwflory , I am currently working on hugo, as i am new to this. I will be asking you if i have any issue.

No problem. You can use this GitHub issue to ask for help. 👍🏻 You may also find this [intern on-boarding guide](https://unicef.github.io/inventory/meta/inventory/intern-guide/) useful as a starting point too.

> _**@Neha9849 wrote…**_
> And i thought of a button in the Navbar. Something like this- ![A button with the GitHub logo with button text, "edit this page."](https://user-images.githubusercontent.com/4721034/153371920-f306f035-68f2-48ab-81c8-809d6113e42d.png "A button with the GitHub logo with button text, \"edit this page.\"")

Makes sense. I think placing the button between the breadcrumbs and the page title could work:

![Screenshot of the top section of an article in the Open Source Inventory, showing the breadcrumbs, page title, and the beginning of the article text.](https://user-images.githubusercontent.com/4721034/153371680-cb2a4449-c5c4-4d07-8ec7-240539918126.png "Screenshot of the top section of an article in the Open Source Inventory, showing the breadcrumbs, page title, and the beginning of the article text.")

> _**@Neha9849 wrote…**_
> Do this community have any channels for diccussions? Lemme me know if there is one :)

We do! We are using Matrix/Element. Details below:

* **URL to chat room**: https://matrix.to/#/#unicef-innovation:matrix.org
* **Docs on getting started with Element**: https://element.io/help
  * **Desktop client**: https://element.io/get-started#download
  * **Web/browser client**: https://app.element.io/

Please say hi once you jump in there. 🙂

**Comment by barcha47** [comment]
Hey @jwflory  I have completed all three initial tasks. PLease assign this to me if issue is still open.

**Comment by jwflory** [comment]
Completed by Neha in PR #88.
