### ISSUE TITLE
Duplication of Home Page in Footer.

### ISSUE THREAD

**Issue by Syed-Ansar** [unicef/inventory-hugo-theme#57]
# Summary
In the https://unicef.github.io/inventory-hugo-theme/ page. There are two home links of same functionality.

# Background
<img width="1440" alt="Screenshot 2022-03-01 at 10 53 25 AM" src="https://user-images.githubusercontent.com/82027712/156112118-c2355937-de22-41b3-bc93-e2daac1a998f.png">

# Details
Only one link should be present there. Another should be removed.

# Outcome

<img width="1440" alt="Screenshot 2022-03-01 at 11 16 55 AM" src="https://user-images.githubusercontent.com/82027712/156112305-d549293c-2879-4391-bc19-599451dfa27c.png">

**Comment by Syed-Ansar** [comment]
@jwflory Can I work on this. Assign it to me.

**Comment by Syed-Ansar** [comment]
Okay @jwflory I will work on it

**Comment by jwflory** [comment]
@Syed-Ansar Great! Feel free to ask any questions in this GitHub Issue as you go.

**Comment by Syed-Ansar** [comment]
> @Syed-Ansar Great! Feel free to ask any questions in this GitHub Issue as you go.

@jwflory Is there any IRC channel, slack, or any mode of communication channel for contributors or developers

**Comment by jwflory** [comment]
> **_@Syed-Ansar wrote…_**
> @jwflory Is there any IRC channel, slack, or any mode of communication channel for contributors or developers

We have a Matrix room set up. You can join using [this link](https://matrix.to/#/#unicef-innovation:matrix.org). Feel free to drop an intro and say hi once you're there! If you never used Matrix before, you can see the [getting started page](https://element.io/get-started) for the Element chat client.

**Comment by Syed-Ansar** [comment]
Thank you @jwflory

**Comment by jwflory** [comment]
@Neha9849 completed this one in PR #80. 🙌🏻  Neha, could you add a comment here so I can assign the issue to you? It will make it easier for me to keep up with contributions over the next month.

**Comment by Neha9849** [comment]
@jwflory I am glad that u merged my PR :)
