### ISSUE TITLE
Outreachy #2: Set up a development environment with the UNICEF Open Source Inventory

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#60]
_Welcome to Outreachy 2022 with @unicef! This is an issue meant for newcomers working on the UNICEF Inventory project. Before working on this project, you should read the [full project profile](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/unicef/#improve-uiux-of-unicef-inventory-and-redesign-site) from the Outreachy website for more background. It will make your first contribution and efforts here easier!_

# Summary

Set up your development environment with UNICEF Open Source Inventory site.

# Background

The UNICEF Inventory theme is one part of this Outreachy project. The other major part is the [UNICEF Open Source Inventory](https://unicef.github.io/inventory/), the main website that uses the UNICEF Inventory theme. The source code for this site is found in the [unicef/inventory repo](https://github.com/unicef/inventory). During the internship, the Open Source Inventory is the main site you will work on to see your changes and improvements go live. So, it is important that you are able to set it up and run it, in addition to the example site in the UNICEF Inventory theme repo.

The purpose of this issue is a milestone in your Outreachy application to @unicef. To complete this issue, your mission is to set up your development environment with the UNICEF Open Source Inventory and share proof of that by uploading a screenshot to this GitHub Issue. Once you have done so, you will be "assigned" to this GitHub Issue as verification you have completed the requirement. You can also provide help and guidance to others who ask for help in this issue if you wish.

This issue will remain open for the full contribution period of this Outreachy round and will close on 22 April (end of contribution period).

# Details

This task is trickier than the last issue because you will need to use [git submodules](https://www.atlassian.com/git/tutorials/git-submodule). For the Open Source Inventory site, there is actually one git repo inside of another. Git submodules make this possible. When you clone the `unicef/inventory` repo, you also need to clone the git submodule that includes the theme found at `unicef/inventory-hugo-theme`. Otherwise, you will be unable to build and preview the site locally with Hugo.

To complete this issue, do the following:

1. First, complete Issue #59.
2. Clone the [unicef/inventory repo](https://github.com/unicef/inventory) to your machine. When cloning, you need to use the `--recurse-submodules` flag.
3. Create a new Team Profile to demonstrate that it works. Team Profiles are profiles for companies funded by the UNICEF Innovation Fund. See an example [here](https://unicef.github.io/inventory/cohorts/blockchain/treejer/). To create a Team Profile, do the following:
    1. Copy the [template profile](https://github.com/unicef/inventory/blob/main/content/cohorts/template.en.adoc) at `content/cohorts/template.en.adoc` to the [`others` directory](https://github.com/unicef/inventory/tree/main/content/cohorts/others).
    2. Change the name of the template file to your GitHub username, e.g. `jwflory.en.adoc`.
    3. Edit the file and make your own changes to the template. What you edit doesn't matter so much – this is just to demonstrate you have mastered this concept.
4. Run `hugo serve` in the terminal and open the example site to see your changes.
5. Take a screenshot of the example Team Profile you created from your browser.
6. Upload the screenshot to this GitHub Issue.

# Outcome

- You successfully set up the UNICEF Open Source Inventory, created a Team Profile, and saw them live from a local preview on your machine.
- You are now ready to move on to the final Outreachy applicant issue, #61.

**Comment by mmldco** [comment]
HI @jwflory , there are two issue that will trip up contributors when they're working on this task.

1. You'll need to add a trailing 's' to the 'Other' folder otherwise contributors will get a 404 error when they try navigating to it.
2. Add an instruction to inform contributors that they'll need to remove the` draft: true` declaration inside their edited template file otherwise it wont show up when they run `hugo serve`.  Alternatively they can run `hugo serve -D` in-order to build draft pages which will show their modified pages.

**Comment by jwflory** [comment]
Hey @mmldco, thanks for coming in here!

> **_@mmldco wrote…_**
>     1. You'll need to add a trailing 's' to the 'Other' folder otherwise contributors will get a 404 error when they try navigating to it.

Not sure I understand what you mean. I'm not getting the 404 Error with the trailing `s`. The profiles that would fit into the _Others_ category would be here:

https://unicef.github.io/inventory/cohorts/other/

But this is a 404 Error for me:

https://unicef.github.io/inventory/cohorts/others/

> **_@mmldco wrote…_**
>     2. Add an instruction to inform contributors that they'll need to remove the` draft: true` declaration inside their edited page otherwise it won't show up when they run `hugo serve`.  Alternatively you can change the hugo serve command above to `hugo serve -D` in-order to build draft pages. This will ensure their draft page show up when the site is built.

Good catch. I think your comment here in this GitHub Issue is sufficient to bring this to attention. Thanks for pointing that detail out!

**Comment by mmldco** [comment]
See the below screenshot for what's causing the 404 error. 

![Screenshot 2022-03-11 at 1 27 19 PM](https://user-images.githubusercontent.com/69677286/157851308-f706e90e-f67b-4e29-b424-6c0608cfd01c.png)

**Comment by mmldco** [comment]
See the below screenshot below to see what I believe is causing the 404 error. 

![Screenshot 2022-03-11 at 1 48 51 PM](https://user-images.githubusercontent.com/69677286/157854763-239f1a6a-156a-489d-a67e-f16845fe1554.png)

**Comment by jwflory** [comment]
@mmldco Oh, I see what you mean now. Great catch! Could you raise a Pull Request to the Open Source Inventory repository to fix this? This is a separate bug from what this issue is about.

**Comment by mmldco** [comment]
@jwflory done.

**Comment by Yavnikaa** [comment]
![Screenshot (208)](https://user-images.githubusercontent.com/56485761/158051709-ce4ddc6f-243b-4117-98bb-f3e75435df95.png)

Completed as instructed!

**Comment by BeeBombshell** [comment]
Hi... I set up the Inventory repo and finished the task as instructed... 😊 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/53828745/158195544-6d4f9e44-c325-4240-a5c7-b1ad5ad30a9f.png">

**Comment by jwflory** [comment]
Nice work @Yavnikaa & @BeeBombshell 👍🏻

**Comment by steph237** [comment]
![inventory2](https://user-images.githubusercontent.com/43364084/158217267-b55b1eee-7fa3-462e-a246-0e44dd1fdb39.png)
Hi I followed the instructions, set up the repo and finished the task

**Comment by jwflory** [comment]
Looks good @steph237, you're ready for Task 3 👍🏻

**Comment by mmldco** [comment]
My submission

![Screenshot 2022-03-17 at 1 46 55 AM](https://user-images.githubusercontent.com/69677286/158703731-c7793b0d-f066-4ce3-a12b-7be8bbca32a8.png)

**Comment by Neha9849** [comment]
Here is mine

![image](https://user-images.githubusercontent.com/85057583/158772743-85a3b36e-f05e-44df-9780-c6ba9fd6a613.png)

**Comment by jwflory** [comment]
Thanks @mmldco and @Neha9849, looking good 👍🏻

**Comment by roli25** [comment]
Completed Task 2 @jwflory 
![Screenshot (457)](https://user-images.githubusercontent.com/59510531/158806992-54a21577-9856-4285-a0fb-d157c21057ab.png)

**Comment by jwflory** [comment]
@roli25 Looks good here 👍🏻

**Comment by gnikita432** [comment]
Hey, @jwflory  I have completed task 2. 
Here is the screenshot 
![image](https://user-images.githubusercontent.com/61223163/159115146-916cfc7f-6b5a-490d-a7ac-d7f6c83e1a53.png)
Thank you!

**Comment by AbihaFatima** [comment]
Hey @jwflory! Completed Task#2
My Submission:
![image](https://user-images.githubusercontent.com/70844041/159910426-b9058066-8859-49b2-9172-988b21a6fa44.png)

**Comment by reeshi-18** [comment]
![image](https://user-images.githubusercontent.com/77070824/160239761-821d1663-e973-4c43-92f3-2295ecfe403d.png)

**Comment by reeshi-18** [comment]
![image](https://user-images.githubusercontent.com/77070824/160239784-16b98575-9b64-4660-b59c-f03ca6d05fda.png)

**Comment by Hydriah** [comment]
Hi  @jwflory @Idadelveloper! Completed Task#2
![Screenshot from 2022-03-27 13-31-56](https://user-images.githubusercontent.com/89812240/160281958-78864e09-e80a-43b9-b5f0-76ebbfb8dc65.png)

**Comment by bl-aire** [comment]
Hello @jwflory, I have completed this task. A picture is attached below.

![blaire](https://user-images.githubusercontent.com/84882370/160302675-c5413159-2678-4e1c-8675-47c1d6ce4fa5.PNG)

**Comment by siddharth628** [comment]
@jwflory, it's done.
<img width="1440" alt="Screenshot 2022-03-28 at 3 39 20 PM" src="https://user-images.githubusercontent.com/73435365/160376292-33ccf005-498f-4b39-93da-77442ee20e35.png">

**Comment by RuthAtem** [comment]
Done
![Screenshot from 2022-03-28 11-56-57](https://user-images.githubusercontent.com/40384565/160383908-a80785a3-70fb-456c-af6a-c8226722af8e.png)

**Comment by ElHombreMorado8** [comment]
It's done

![image](https://user-images.githubusercontent.com/86472204/160464798-d4f9b916-32aa-41f0-8b4d-69116037e13b.png)

![image](https://user-images.githubusercontent.com/86472204/160464510-1a8b67e9-880a-4c3e-8df3-500e37c422d8.png)

**Comment by chaitri19** [comment]
@jwflory it's done
![Outreachy-1](https://user-images.githubusercontent.com/85275171/160578906-19baeceb-dca0-47ef-862d-557b438a4db6.png)

**Comment by EmmanuelOloke** [comment]
Hello, @jwflory @Idadelveloper. Task 2 is completed, find attached the screenshot below.


<img width="1440" alt="Screenshot 2022-03-29 at 13 33 30" src="https://user-images.githubusercontent.com/16335826/160612308-5737231a-9f9c-4744-a8e7-180a43d89aee.png">

**Comment by barcha47** [comment]
Hello @jwflory  i am having little trouble, please take a look. when i try to run hugo server, my local host direclty leads to pervious cloned repo, i can't open different site via hugo.
![2](https://user-images.githubusercontent.com/66128370/160713820-9f29f820-1b7b-4729-8795-514f9b34d7f2.PNG)

**Comment by jwflory** [comment]
@gnikita432 @AbihaFatima @Hydriah @bl-aire @siddharth628 @RuthAtem @ElHombreMorado8 @chaitri19 @EmmanuelOloke Looks good, nice work! 👍🏻 You're clear to take on the third onboarding issue if you have not already. As I said in the previous issue, GitHub only lets me assign ten people to one issue, but that isn't a key metric used here anyways.

@reeshi-18 I see your screenshot of the Profiles, but were you able to create a new profile in the _Others_ category?

**_@kbetty wrote…_**
> I get an error while trying task 2 after following the stipulated steps.
> 
> ```js
> pensource@opensource:~/Documents/Outreachy/inventory$ hugo serve
> Error: add site dependencies: load resources: loading translations: "/home/opensource/Documents/Outreachy/inventory/themes/inventory/i18n/en.yaml:1:1": 
> failed to load translations: unable to parse translation #0 because missing "id" key
> map[footer:map[legal:Find legal information and policies related to {{ $.Site.Params.brand.parent_org_name }}'s digital communications.]]
> ```
> 
> I got this same error when doing my first task and deleting the files: `en.yaml` and `fr.yaml` solved the issue but this time this doesn't solve the issue. I have tried different solutions but am failing to figure out the issue. Thanks for the help!

The way translations were managed changed at one point. There are localized strings in the theme. Did you have an older clone of the repository? Also, could you describe your environment more? What operating system are you using? What version of Hugo do you have installed? You may also need a newer version of Hugo since some of our site features are not supported in older versions of Hugo. (For example, the Ubuntu repository package is old and doesn't work with the Open Source Inventory site.)

**_@barcha47 wrote…_**
> Hello @jwflory i am having little trouble, please take a look. when i try to run hugo server, my localhost directly leads to **pervious cloned repo**, i can't change localhost to open different site.

You add the `--theme` flag to specify a different directory for the site theme, but this is not expected for how we run and deploy the sites. Try removing the flag while inside the Open Source Inventory site and see if anything changes.

**Comment by barcha47** [comment]
Thank you @jwflory for clearing the concepts. Here's my task 2 completed.
![t2](https://user-images.githubusercontent.com/66128370/160798678-cb1b43b4-c4bc-44f7-801c-272d0cc8d8e2.PNG)

**Comment by jwflory** [comment]
@barcha47 Looks good! You're cleared to work on the third and final onboarding task 👍🏻

**Comment by kbetty** [comment]
Thanks @jwflory for the support. Am using Ubuntu 20.4 and the hugo version is:

```js
opensource@opensource:~$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

```
I didn't have any older repository on my machine for inventory. Have been trying out different solution provided on stack-overflow but none of them is working for me.

**Comment by jwflory** [comment]
@kbetty Aha. This is an old version of Hugo that does not support localizations bundled in the theme. The current release of Hugo is v0.96.0. I suggest upgrading to the latest version of Hugo, and this issue will be resolved for you.

The approach I would take is to first uninstall the Ubuntu system package for Hugo, and then follow the instructions on the Hugo website to [install a binary](https://gohugo.io/getting-started/installing/#binary-cross-platform). You can find the binaries in the [latest release](https://github.com/gohugoio/hugo/releases) from GitHub. Once you install the new version of Hugo, test it with `hugo version` and then try building the site again.

**Comment by kbetty** [comment]
Thanks @jwflory for the guidance. Have followed it carefull and installed the newest hugo version v96.0. Then cloned a fresh repo and made the suggested changes and on running the command hugo serve, I get this error

```js
opensource@opensource:~/Desktop/inventory$ hugo serve
Start building sites … 
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=mage
Error: Error building site: "/home/opensource/Desktop/inventory/content/faq/_index.en.adoc:8:1": failed to extract shortcode: template for shortcode "faq" not found
Built in 43 ms
opensource@opensource:~/Desktop/inventory$ 


```

**Comment by Abbiefied** [comment]
Hello @jwflory , I have completed the task 
![image](https://user-images.githubusercontent.com/88349524/160917154-f4414553-c567-4876-8c9d-7dd2267cbfcb.png)

**Comment by Abbiefied** [comment]
> Thanks @jwflory for the guidance. Have followed it carefull and installed the newest hugo version v96.0. Then cloned a fresh repo and made the suggested changes and on running the command hugo serve, I get this error
> 
> ```js
> opensource@opensource:~/Desktop/inventory$ hugo serve
> Start building sites … 
> hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=mage
> Error: Error building site: "/home/opensource/Desktop/inventory/content/faq/_index.en.adoc:8:1": failed to extract shortcode: template for shortcode "faq" not found
> Built in 43 ms
> opensource@opensource:~/Desktop/inventory$ 
> ```

@kbetty I also got this error when I installed the binary directly without specifying the directory. I solved it by creating a folder **'Hugo'** in C: , then created two subfolders **'bin'** and **'Sites'** in the parent folder 'Hugo'. In the terminal, I changed my directory to /Hugo/bin then I installed hugo with this command **wget https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_0.96.0_Linux-64bit.tar.gz -O -   | tar -xvz**

Add **C:\Hugo\bin** to the environment path from the control panel
After the steps above clone the repository again and make the changes, I hope it helps

**Comment by jwflory** [comment]
@Abbiefied Looks good, thanks! 👍🏻 You're good to go here.

> **_@kbetty wrote…_**
> Thanks @jwflory for the guidance. Have followed it carefull and installed the newest hugo version v96.0. Then cloned a fresh repo and made the suggested changes and on running the command hugo serve, I get this error

You can see the above advice if you are on Windows. But if you are on Linux as I suspect you are, this error might happen if you have not cloned the git submodule for the Open Source Inventory. This is in Step 2 of the above. If you have already cloned the repo but don't have the submodule ready, you can use these commands to install the git submodule on an already-cloned repo:

```sh
cd /path/to/inventory/
git submodule update --init
git submodule update --remote
```

It should clone a new git repo for the inventory-hugo-theme repo. Then, this error will go away if the submodule was not also installed.

**Comment by yokwejuste** [comment]
I'm done with this task @jwflory 
![Screenshot from 2022-03-31 12-47-52](https://user-images.githubusercontent.com/71908316/161048491-c4d0097b-6b61-43f5-91a8-1f9c87a9f71e.png)

**Comment by jwflory** [comment]
@yokwejuste Looks good, nice work! 👍🏻

**Comment by ragini-gp** [comment]
@Idadelveloper @jwflory Please can you tell me ,in 3rd point of details of this contribution, How to copy the template profile from where ?

**Comment by ragini-gp** [comment]
@Idadelveloper @jwflory Please help me out. I am facing an issue. When I try to run hugo command, It shows the previous website, Thanks in advance! pag
![Screenshot (1568)](https://user-images.githubusercontent.com/97662858/161254800-29234610-3b1e-40e2-9668-c9fde6a07df7.png)
e

**Comment by barcha47** [comment]
hey @ragini-gp , go back to root directory and then run the command.  It will work.

**Comment by ragini-gp** [comment]
> hey @ragini-gp , go back to root directory and then run the command. It will work.
![Screenshot (1569)](https://user-images.githubusercontent.com/97662858/161356869-65494c83-06f2-45f4-8841-f57c5b9e4802.png)
@barcha47

**Comment by yokwejuste** [comment]
> > hey @ragini-gp , go back to root directory and then run the command. It will work.
> > ![Screenshot (1569)](https://user-images.githubusercontent.com/97662858/161356869-65494c83-06f2-45f4-8841-f57c5b9e4802.png)
> > @barcha47

try  `hugo serve -D` by the way what is your hugo version?

**Comment by ragini-gp** [comment]
> > > hey @ragini-gp , go back to root directory and then run the command. It will work.
> > > ![Screenshot (1569)](https://user-images.githubusercontent.com/97662858/161356869-65494c83-06f2-45f4-8841-f57c5b9e4802.png)
> > > @barcha47
> 
> try `hugo serve -D` by the way what is your hugo version?

@yokwejusteHugo version- hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb windows/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio

**Comment by ragini-gp** [comment]
> > > hey @ragini-gp , go back to root directory and then run the command. It will work.
> > > ![Screenshot (1569)](https://user-images.githubusercontent.com/97662858/161356869-65494c83-06f2-45f4-8841-f57c5b9e4802.png)
> > > @barcha47
> 
> try `hugo serve -D` by the way what is your hugo version?

@yokwejuste same error
![Screenshot (1572)](https://user-images.githubusercontent.com/97662858/161378698-05935722-d042-406c-8a92-0e3982319be2.png)

**Comment by manasvvi1** [comment]
Hey @jwflory @Idadelveloper 
Please review my work and suggest any required changes
Thank You

![image](https://user-images.githubusercontent.com/77732100/161386751-cd736784-d288-4eb7-9c26-bfb0a2565d1b.png)

**Comment by ragini-gp** [comment]
@jwflory @Idadelveloper , I am getting an error
![Screenshot (1573)](https://user-images.githubusercontent.com/97662858/161456987-cd6f1e3f-2bf7-4eb9-a635-b2fd8d7ad262.png)

**Comment by jwflory** [comment]
> **_@ragini-gp wrote…_**
> I am getting an error

This error is because you do not have `asciidoctor` installed. You need it to build content in the Open Source Inventory. See the [O.S. Inventory developer environment guide](https://github.com/unicef/inventory/blob/main/.github/CONTRIBUTING.md#create-a-local-environment-of-the-inventory) and the [Asciidoctor installation docs](https://docs.asciidoctor.org/asciidoctor/latest/install/). Then you should be able to build the site.

> **_@manasvvi1 wrote…_**
> Please review my work and suggest any required changes Thank You

Hi @manasvvi1, it looks right! 👍🏻 Good work.

**Comment by ragini-gp** [comment]
@jwflory Thankyou so much for your guidance. I have made the changes, Please check, whether it is correct or not
![Screenshot (1575)](https://user-images.githubusercontent.com/97662858/161768445-3ff42474-5b68-4e7c-811b-f6a1cdd575cc.png)

Thanks in advance

**Comment by jwflory** [comment]
@ragini-gp It looks good! You are ready to tackle #61.

However, I will note there is a lack of tasks to work on right now in the project after the starter issues. I recently [closed the project for new applicants](https://www.outreachy.org/communities/cfp/unicef/) in the Outreachy portal. It is a very competitive round and we only have one funded internship. It may be strategic to look at other communities with fewer applicants for their mentored projects. I know the [Fedora Project](https://www.outreachy.org/communities/cfp/fedora/) is one other excellent community and they are funding three interns.

**Comment by jwflory** [comment]
Thank you to everyone who participated in our project for the Outreachy May 2022 round! For those of you beginning your open source journey here, I hope this is just the first stop of many for you in your journey. ☺️ Wishing you the best from the UNICEF Office of Innovation. 🚀
