### ISSUE TITLE
Outreachy #3: Use a git feature branch from your fork in the git submodule to show changes

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#61]
_Welcome to Outreachy 2022 with @unicef! This is an issue meant for newcomers working on the UNICEF Inventory project. Before working on this project, you should read the [full project profile](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/unicef/#improve-uiux-of-unicef-inventory-and-redesign-site) from the Outreachy website for more background. It will make your first contribution and efforts here easier!_

# Summary

Use a git feature branch from your forked repository of this theme in the UNICEF Open Source Inventory for testing changes and improvements to the theme.

# Background

One of the trickiest parts to learn when working on the UNICEF Open Source Inventory and the Inventory theme is git submodules and the flow of how to test your changes. This issue will get you to better understand the workflow for testing and contributing changes to the site. After completing this issue, you will be ready to tackle another "good first issue" to fix a bug or improve something in the actual theme! Before beginning, you need to first make a fork of this repository (`unicef/inventory-hugo-theme`) and clone the forked repo locally to your machine.

The purpose of this issue is a milestone in your Outreachy application to @unicef. To complete this issue, your mission is to use a forked repo in a git feature branch with changes to the theme, and use that feature branch from your development environment with the UNICEF Open Source Inventory. You will share proof of that by sharing a link to your git feature branch in your forked git repo. Once you have done so, you will be "assigned" to this GitHub Issue as verification you have completed the requirement. You can also provide help and guidance to others who ask for help in this issue if you wish.

This issue will remain open for the full contribution period of this Outreachy round and will close on 22 April (end of contribution period).

# Details

This task builds on the knowledge you gained working on #59 and #60. It may be tricky at first, but getting the hang of this will make your future contributions much easier!

To complete this issue, do the following:

1. First, complete Issues #59 and #60.
2. Fork the `unicef/inventory-hugo-theme` repository to your GitHub account. Clone the forked repo locally to your machine.
3. Create a new [git feature branch]() in your forked repo. Name the git branch anything you like.
4. In the new git branch, edit the `<title>` HTML attribute in [`layouts/partials/head.html`](https://github.com/unicef/inventory-hugo-theme/blob/main/layouts/partials/head.html#L3). Change it from `{{ .Title }}` to your GitHub username, e.g. `@jwflory`.
5. Commit to your changes to the new git branch. Push the git branch to your forked repo.
6. Leave your forked repo. Go back to where you cloned the UNICEF Open Source Inventory site in #60. Once you are back in that project, change directories to `themes/inventory/`.
7. Type `git remote -v`. You should see `github.com/unicef/inventory-hugo-theme`.
8. Now, add your forked repo as a new remote. Use `git remote add fork <URL to your forked repo>`.
9. Use `git fetch fork` to get the branches from your forked repo.
10. Change the git branch in the git submodule to the git branch you pushed in Step 5. This will look like `git checkout fork <branch name>`.
11. Go back to the root directory of the Open Source Inventory (`cd ../../`).
12. Run `hugo serve` in the terminal and open the example site to see your changes.
13. In the browser tab bar, do you see your GitHub username instead of `UNICEF O.S. Inventory`?
14. Come back to this GitHub Issue. Share a link to your forked git repository and the git feature branch you pushed earlier.

Congrats! You have now completed all three of the initial tasks for this @unicef Outreachy project.

# Outcome

- You successfully used a git feature branch to make changes, pushed them to your forked repo, and used the git feature branch to see your changes from the git submodule in the UNICEF Open Source Inventory site.
- You are now ready to tackle a regular "good first issue" and write some code.

**Comment by Yavnikaa** [comment]
Yes, I could see my username in place of the title.

My forked github repository: https://github.com/Yavnikaa/inventory-hugo-theme.git
My pushed branch: https://github.com/Yavnikaa/inventory-hugo-theme/tree/milestone

I have completed all the three tasks as instructed. Please review them and once and let me know if there's anything that still needs to be done! :')

**Comment by BeeBombshell** [comment]
Hi... I completed this issue as per the instructions and could see my username in the browser tab... 😊 

The links to my forked GitHub repo and the feature branch are as follows:

- Forked GitHub Repo: https://github.com/BeeBombshell/inventory-hugo-theme.git
- Feature Branch: https://github.com/BeeBombshell/inventory-hugo-theme/tree/task3

**Comment by jwflory** [comment]
Looking good @Yavnikaa & @BeeBombshell! You both look set to work on the project and take on a bigger task now. I am working on the contribution guidelines for this repository still, but the best practice, for now, is to look at the issues labeled as [`I: good first issue`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+good+first+issue%22) and/or [`I: help wanted`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+help+wanted%22). See if it is already assigned to someone. If not, you can make a comment requesting to work on it and to get it assigned to you.

**Comment by steph237** [comment]
hey.... I followed the instructions and I could see my user name in the browser tab 
Forked Github repo: https://github.com/steph237/inventory-hugo-theme-1.git
Feature Branch : https://github.com/steph237/inventory-hugo-theme-1/tree/newSteph
I have completed all three tasks and I will be waiting if there's anything else i can do

**Comment by jwflory** [comment]
Thanks @steph237, nice work 👍🏻 Using a feature branch as the workflow for submitting contributions will make collaboration easier. You're all set to take on your first code task. The best practice, for now, is to look at the issues labeled as [`I: good first issue`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+good+first+issue%22) and/or [`I: help wanted`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+help+wanted%22). See if it is already assigned to someone. If not, you can make a comment requesting to work on it and to get it assigned to you.

**Comment by mmldco** [comment]
My Submission

Forked Repo: https://github.com/mmldco/inventory-hugo-theme
Feature Branch: https://github.com/mmldco/inventory-hugo-theme/tree/outreachy

**Comment by jwflory** [comment]
Thanks @mmldco, you're all set! 👍🏻 One tip: don't forget to periodically update your fork's `main` branch with new commits added to the UNICEF `main` branch. You can do that most easily by checking out and pulling changes:

```sh
cd /path/to/repo/
git checkout main
git pull git@github.com:unicef/inventory-hugo-theme.git
git push origin main
```

Alternatively, you can add this repo as a remote to make it easier:

```sh
cd /path/to/repo/
git remote add upstream git@github.com:unicef/inventory-hugo-theme.git
git fetch upstream
git checkout main
git pull upstream main
git push origin main
```

**Comment by Neha9849** [comment]
Hey! I Followed your instructions and here is my submission -
Forked repo : https://github.com/Neha9849/inventory-hugo-theme
Feature Branch : https://github.com/Neha9849/inventory-hugo-theme/tree/changing-title

**Comment by reeshi-18** [comment]
hi @jwflory @Idadelveloper completed all three tasks!
Feature branch: https://github.com/reeshi-18/inventory-hugo-theme/tree/reeshi
Forked repo: https://github.com/reeshi-18/inventory-hugo-theme

**Comment by RuthAtem** [comment]
Hello, again @jwflory @Idadelveloper. I have completed the 3 initial tasks. n the browser tab bar, I can see my GitHub username instead. It was fun setting up.
Links to my:
Forked repo: https://github.com/RuthAtem/inventory-hugo-theme.git  
Feature branch: https://github.com/RuthAtem/inventory-hugo-theme/tree/dev

**Comment by bl-aire** [comment]
Hello @jwflory 

I followed the instructions stated above and I have completed this task. The links to my forked repository and feature branch are here:
Repository: https://github.com/bl-aire/inventory-hugo-theme
Git feature branch: https://github.com/bl-aire/inventory-hugo-theme/tree/task_three

**Comment by ElHombreMorado8** [comment]
- Repository: https://github.com/ElHombreMorado8/inventory-hugo-theme
- Git feature branch: https://github.com/ElHombreMorado8/inventory-hugo-theme/tree/example_branch

**Comment by jwflory** [comment]
@Neha9849 @AbihaFatima @reeshi-18 @RuthAtem @bl-aire @ElHombreMorado8 Everything looks good! You're all complete with the onboarding tasks and you can take on a more advanced issue. I know many of you have commented on other issues and I'm working on catching up this week.

You are also welcome to propose your own issues as feature requests or bug reports if there are improvements you think could be made to the site. The issue templates can help you with proposing a change and getting feedback on it.

**Comment by Hydriah** [comment]
Hello,  @jwflory @Idadelveloper. I have completed the 3 initial tasks. here is 
Links to my:
Forked repo: https://github.com/Hydriah/inventory-hugo-theme
Feature branch: https://github.com/Hydriah/inventory-hugo-theme/tree/review

**Comment by jwflory** [comment]
@Hydriah Looks good, nice work! 👍🏻 You're ready to tackle your first development issue. The best practice, for now, is to look at the issues labeled as [`I: good first issue`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+good+first+issue%22) and/or [`I: help wanted`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+help+wanted%22). See if it is already assigned to someone. If not, you can make a comment requesting to work on it and to get it assigned to you.

If you have any questions in the meantime, we have a Matrix room set up. You can join using [this link](https://matrix.to/#/#unicef-innovation:matrix.org). Feel free to drop an intro and say hi once you're there! If you never used Matrix before, you can see the [getting started page](https://element.io/get-started) for the Element chat client.

**Comment by barcha47** [comment]
Hey @jwflory , I have completed all 3 initial tasks. 
Hey are my links:
**Forked Repository:** https://github.com/barcha47/inventory-hugo-theme
**Git feature branch:** https://github.com/barcha47/inventory-hugo-theme/tree/barcha47

**Comment by EmmanuelOloke** [comment]
Hello @jwflorym just completed this third issue. Below are the required links

Forked Repository: https://github.com/EmmanuelOloke/inventory-hugo-theme.git
Git Feature Branch: https://github.com/EmmanuelOloke/inventory-hugo-theme/tree/EmmanuelOloke-Unicef

**Comment by jwflory** [comment]
@siddharth628 @barcha47 @EmmanuelOloke Nice work! You all are set to move on to another issue for contributing. The best practice, for now, is to look at the issues labeled as [`I: good first issue`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+good+first+issue%22) and/or [`I: help wanted`](https://github.com/unicef/inventory-hugo-theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22I%3A+help+wanted%22). See if it is already assigned to someone. If not, you can make a comment requesting to work on it and to get it assigned to you.

If you have any questions in the meantime, we have a Matrix room set up. You can join using [this link](https://matrix.to/#/#unicef-innovation:matrix.org). Feel free to drop an intro and say hi once you're there! If you never used Matrix before, you can see the [getting started page](https://element.io/get-started) for the Element chat client.

**Comment by Abbiefied** [comment]
Hello @jwflory , I have completed task #3 
Forked Repository : https://github.com/Abbiefied/inventory-hugo-theme.git
Git Feature Branch: https://github.com/Abbiefied/inventory-hugo-theme/tree/abbiefied

**Comment by yokwejuste** [comment]
Greetings @jwflory, still following up on issues. For now, I'm done with this one.

The Forked Repo:  https://github.com/yokwejuste/inventory-hugo-theme

The Git feature branch: https://github.com/yokwejuste/inventory-hugo-theme/tree/wise-branch

Any task available, feel free to assign me.

**Comment by jwflory** [comment]
Thanks @Abbiefied and @yokwejuste, looks good! See the previous instructions for the next steps.

**Comment by manasvvi1** [comment]
Hey @jwflory @Idadelveloper 
I have completed this issue. Please review it.

Forked Repo: https://github.com/manasvvi1/inventory-hugo-theme.git
Git feature branch: https://github.com/manasvvi1/inventory-hugo-theme/tree/manasvvi1

If there are any further steps to be done, please assign me.
Thanks

**Comment by jwflory** [comment]
@chaitri19 @manasvvi1 Nice work! You both completed all of the Outreachy onboarding issues.

You are free to work on other issues, although at the moment, everything is assigned. We are at capacity for contributions right now! This may change, but it is good to be strategic by looking at other communities with fewer applicants for their mentored projects. I [closed the project for new applicants](https://www.outreachy.org/communities/cfp/unicef/) in the Outreachy portal. I know the [Fedora Project](https://www.outreachy.org/communities/cfp/fedora/) is one other excellent community and they are funding three interns.

**Comment by ragini-gp** [comment]
@jwflory , I have completed task 3, Please go through it.
Forked repo: https://github.com/ragini-gp/inventory-hugo-theme.git
Feature branch -https://github.com/ragini-gp/inventory-hugo-theme/tree/feature
I saw my user name in browser tab bar.
Please let me know the next task

**Comment by jwflory** [comment]
@ragini-gp The feature branch looks good, nice work! Currently, there are not any unassigned issues. The project had a huge interest and the available tasks were picked up. You can also see previous comments on this issue for guidance.

**Comment by jwflory** [comment]
Thank you to everyone who participated in our project for the Outreachy May 2022 round! For those of you beginning your open source journey here, I hope this is just the first stop of many for you in your journey. ☺️ Wishing you the best from the UNICEF Office of Innovation. 🚀
