### ISSUE TITLE
Support a new AsciiDoc admonition block: NOTE

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#63]
# Summary

When an AsciiDoc `NOTE` admonition is used, it should be more distinguished from the rest of the content on a page.

# Background

**Is the new feature related to a problem? Describe the problem**: AsciiDoc supports several kinds of [admonitions](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions), but when they are used, they are not visually distinguished:

![Screenshot of an AsciiDoc admonition when used in the Inventory theme](https://user-images.githubusercontent.com/4721034/157732830-b326108f-bfce-4676-a898-2b8f02ca6173.png "Screenshot of an AsciiDoc admonition when used in the Inventory theme")

**What does the new feature look like to you?**: Each admonition should use a unique icon and color to visually represent the admonition. It should be visually distinguished from the rest of the content on a page.

# Details

There are many AsciiDoc admonitions, and a `NOTE` is just one type. For icons, we should take an approach like using a common set of open source icons that can be used for all admonitions. This way, they will also be more similarly matched to each other. Additionally, when each admonition is used, AsciiDoc+Hugo will automatically create HTML `id` and `class` attributes so they can be styled further with layouts and CSS. To see these attributes, you will need to edit a content page, add the admonition, run the Hugo server, and use the browser tools to inspect the element on the rendered page to see what the HTML attributes are.

For the `NOTE` admonition, this could be a blue color with an informational icon. It shouldn't be too distracting from the rest of the page—it is just a casual note.

![Screenshot of an example NOTE admonition from another site.](https://user-images.githubusercontent.com/4721034/157733595-e9fbea12-72d9-40a9-b878-9391fce5f358.png "Screenshot of an example NOTE admonition from another site.")

# Outcome

`NOTE` admonitions are supported with a unique appearance in the rendered site when used in content files.

**Comment by BeeBombshell** [comment]
Hi @jwflory, can I work on this issue? 😊

**Comment by jwflory** [comment]
@BeeBombshell Sure, you can take this one up 👍🏻 

Note that for the icon set used, you will need to coordinate with @Yavnikaa with her change for #64. You can still work on styling the alert box and customizing the HTML, but stay posted for the common icon set to use for both types of admonitions.

**Comment by jwflory** [comment]
@BeeBombshell This looks on the right track. You can also reference this sample set put together by @Yavnikaa in #64:

![Sample set of admonitions with logo, from Yavnika in Issue #64](https://user-images.githubusercontent.com/4721034/159073920-6671e001-4dd3-402e-84a7-1a82254b8656.png "Sample set of admonitions with logo, from Yavnika in Issue #64")

Since the work started on #63 and #64 at about the same time, we will likely need to make adjustments to both implementations. I suggest using [Feather Icons](https://feathericons.com/) as the icon set for all admonitions. It will be an iterative process 😀

I suggest going ahead to work on the NOTE admonition and open a new Pull Request. We'll coordinate along with progress in #64. 👍🏻 Looking forward to seeing your PR! Have a good weekend.

**Comment by BeeBombshell** [comment]
@jwflory For creating the admonition, I've used the previously installed plugin `Themify Icons`. I'm creating a PR with my design for the `NOTE` admonition. Kindly take a look... Enjoy your weekend! 😄

**Comment by Yavnikaa** [comment]
Hey @BeeBombshell ! I have a little doubt. Is your PR changing the exact admonition block we are talking about? How did you handle the table structure and capitalising the hardcoded text of the admonition block (attaching screenshot of what I'm talking about)

![image](https://user-images.githubusercontent.com/56485761/159081202-3f60071a-70ed-484a-bb37-3bc9f2fe5077.png)

**Comment by BeeBombshell** [comment]
@Yavnikaa I was going through the `shortcodes` when I found the `notice` class. Currently, it has three custom admonitions - **Note**, **Tip**, and **Info**. Each admonition has its separate styling in the CSS file. I customized the CSS file to meet the required design...

However, I too was a little confused as to why there existed a different shortcode class by the name `notice`. This class can be used for admonitions and we can style them by changing the style sheet. Although, whenever a new user needs to use an admonition, he/she would have to use the `notice` class instead...

So I was wondering if we could change the name of the class to avoid confusion as the class has all necessary requirements to create admonition blocks... 😊

**Comment by jwflory** [comment]
Some important sleuthing happened here! There are some untouched parts of the theme like these shortcodes. 😅 The shortcodes for _Note_, _Tip_, _Info_, and _Warning_ already exist and also give us greater control over the HTML structure. Since these shortcodes can be used for any kind of content (e.g. Markdown or Asciidoc), they seem like the superior choice for creating and managing these admonitions.

So, here is what I propose we do instead.

Instead of creating support for Asciidoc admonitions and maintaining two different appearances for the admonitions, we can rally behind one and stick with what already exists in the theme. We can leave Note, Tip, Info, and Warning as they are currently, but add Caution (#66) and Important (#64). I think @BeeBombshell can continue to work on these and @Yavnikaa can begin focusing on #35. I realize now that these admonition block issues should have been grouped together into the same task.

A note for the future. For downstreams, we'll need to make a clear note about these shortcodes and that they exist. Writers should avoid using markup language syntax for these types of markup. This is probably part of another effort of cleaning up the example site into more useful docs about the theme itself.
