### ISSUE TITLE
Support a new AsciiDoc admonition block: TIP

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#65]
# Summary

When an AsciiDoc `TIP` admonition is used, it should be more distinguished from the rest of the content on a page.

# Background

**Is the new feature related to a problem? Describe the problem**: AsciiDoc supports several kinds of [admonitions](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions), but when they are used, they are not visually distinguished:

![Screenshot of an AsciiDoc admonition when used in the Inventory theme](https://user-images.githubusercontent.com/4721034/157732830-b326108f-bfce-4676-a898-2b8f02ca6173.png "Screenshot of an AsciiDoc admonition when used in the Inventory theme")

**What does the new feature look like to you?**: Each admonition should use a unique icon and color to visually represent the admonition. It should be visually distinguished from the rest of the content on a page.

# Details

There are many AsciiDoc admonitions, and a `TIP` is just one type. For icons, we should take an approach like using a common set of open source icons that can be used for all admonitions. This way, they will also be more similarly matched to each other. Additionally, when each admonition is used, AsciiDoc+Hugo will automatically create HTML `id` and `class` attributes so they can be styled further with layouts and CSS. To see these attributes, you will need to edit a content page, add the admonition, run the Hugo server, and use the browser tools to inspect the element on the rendered page to see what the HTML attributes are.

For the `TIP` admonition, this could be a green color with an idea-like icon. It shouldn't be too distracting from the rest of the page—it is just a casual tip.

![Screenshot of an example TIP admonition from another site.](https://user-images.githubusercontent.com/4721034/157734585-58620a9a-b737-43b5-ac35-cc242ec00054.png "Screenshot of an example TIP admonition from another site.")

# Outcome

`TIP` admonitions are supported with a unique appearance in the rendered site when used in content files.

**Comment by BeeBombshell** [comment]
Hi @jwflory, I'd like to work on this issue. I wish to propose similar changes as mentioned in PR #75. 😄

**Comment by jwflory** [comment]
Per the [note in #63](https://github.com/unicef/inventory-hugo-theme/issues/63#issuecomment-1082635183) and the change in scope, I am closing this issue as `wontfix` and we can instead add new admonitions for #64 and #66.
