### ISSUE TITLE
Support a new AsciiDoc admonition block: CAUTION

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#66]
# Summary

When an AsciiDoc `CAUTION` admonition is used, it should be more distinguished from the rest of the content on a page.

# Background

**Is the new feature related to a problem? Describe the problem**: AsciiDoc supports several kinds of [admonitions](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions), but when they are used, they are not visually distinguished:

![Screenshot of an AsciiDoc admonition when used in the Inventory theme](https://user-images.githubusercontent.com/4721034/157732830-b326108f-bfce-4676-a898-2b8f02ca6173.png "Screenshot of an AsciiDoc admonition when used in the Inventory theme")

**What does the new feature look like to you?**: Each admonition should use a unique icon and color to visually represent the admonition. It should be visually distinguished from the rest of the content on a page.

# Details

There are many AsciiDoc admonitions, and a `CAUTION` is just one type. For icons, we should take an approach like using a common set of open source icons that can be used for all admonitions. This way, they will also be more similarly matched to each other. Additionally, when each admonition is used, AsciiDoc+Hugo will automatically create HTML `id` and `class` attributes so they can be styled further with layouts and CSS. To see these attributes, you will need to edit a content page, add the admonition, run the Hugo server, and use the browser tools to inspect the element on the rendered page to see what the HTML attributes are.

For the `CAUTION` admonition, this could be a yellow color with an alerting icon. It should catch the user's attention from the rest of the content—it may be an important advisory note, but it is not as severe as a warning or an important note.

![Screenshot of an example CAUTION admonition from another site.](https://user-images.githubusercontent.com/4721034/157738043-86c854c1-8497-4ce7-8fef-fc87cacc9d4f.png "Screenshot of an example CAUTION admonition from another site.")

# Outcome

`CAUTION` admonitions are supported with a unique appearance in the rendered site when used in content files.

**Comment by chaitri19** [comment]
@jwflory Can I work on this issue if it is not assigned to anybody??

**Comment by yokwejuste** [comment]
@jwflory assign me to this issue, the PR is ready already.

**Comment by jwflory** [comment]
Sorry, I was unable to assign this issue to @BeeBombshell. This was added in PR #83.

I would also like to note that I [closed the project for new applicants](https://www.outreachy.org/communities/cfp/unicef/) in the Outreachy portal. It is a very competitive round and we only have one funded internship. It may be strategic to look at other communities with fewer applicants for their mentored projects. I know the [Fedora Project](https://www.outreachy.org/communities/cfp/fedora/) is one other excellent community and they are funding three interns.
