### ISSUE TITLE
Add support for categories as external links

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#69]
# Summary

Allow the creation of a special category on the site home page to link to an external website, instead of linking to an index page within the same site.

# Background

**Is the new feature related to a problem? Describe the problem**: In the future, the UNICEF Open Source Inventory will be restructured around the [Digital Public Goods Standard](https://digitalpublicgoods.net/standard/). While the site will contain content focused around the Standard, it may also include links out. For example, with DPG Standard #1 about the SDGs, we will want to direct the user to the [UN SDGs website](https://sdgs.un.org/goals).

**What does the new feature look like to you?**: It might look like this, and clicking on the category would take you to `sdgs.un.org/goals`. Maybe it would also have an icon to distinguish it as an external link, so it does not appear the same as other categories on the site:

![Screenshot of a sample category that would point to the Sustainable Development Goals website.](https://user-images.githubusercontent.com/4721034/157895312-3926ab5e-f8ac-41a7-a720-bb9648bd2717.png "Screenshot of a sample category that would point to the Sustainable Development Goals website.")

**Describe any alternatives considered**: We could create a new category the Sustainable Development Goals with an index page that then links to the UN Sustainable Development Goals. I believe this is redundant and would be better achieved by creating this "special" kind of category.

# Details

This issue needs research before diving in. What does an implementation look like and how could it work? There are two ideas I have, but they need more research to determine which one is easiest to maintain:

1. Create the special category from the Hugo `config.yml`. The category appears on the site home page, but there are no files stored in `content/`. This would have the lightest footprint, but how it would be arranged with other categories needs thought.
2. Create a new category in the `content/` directory, e.g. `content/sdgs/_index.en.adoc`. Use special front-matter to indicate the category is a redirect category. When the user goes to `unicef.github.io/exampleSite/sdgs/`, it would redirect them to the site specified in the `_index.en.adoc` front-matter.

# Outcome

Better user experience for linking out to external websites and resources at the top-level of an Inventory theme website.

**Comment by bl-aire** [comment]
Can I work on this please?

**Comment by jwflory** [comment]
@bl-aire Would you prefer this issue or #28? For the purposes of the Outreachy contribution phase, it is best if each applicant only takes on one issue at a time. I think this one is more approachable.

**Comment by bl-aire** [comment]
I would love to start with this. While I am at it, I will research about GitHub REST API and how I can approach #28

**Comment by jwflory** [comment]
@bl-aire Sounds good! Looking at the original issue comment, I think the second option explained under _Details_ is the most achievable solution. I could be wrong, but this is my hunch.

Do you feel like you have the information you need to move forward? Are there any questions I can clarify for you? Let me know how I can help you to be successful. 🙌🏻

**Comment by bl-aire** [comment]
@jwflory Thank you.

I will give updates and ask questions when I get stuck as I make progress.

**Comment by jwflory** [comment]
Sounds good. If you are able to share an update by the end of the week, that will help keep things moving 👍🏻

**Comment by bl-aire** [comment]
I definitely will.

**Comment by bl-aire** [comment]
Hello @jwflory,

Over the past few days I researched how to approach the issue on Hugo’s official documentation and discussion forums. The closest I have gotten to finding answers so far is using front matter variables like Aliases and urls.

For Aliases, the use cases I saw aren’t related to the feature this issue is to achieve 

And having the external link I want users directed to as the url only added it to the base url and I get a 404 error on clicking the category I created.

I was able to achieve the result in the video below by creating a new category and using the markdown syntax for referencing external links but I’d love to get clarity so I’d know if I achieved what is required for this issue or there are resources I can study to achieve better results.

https://user-images.githubusercontent.com/84882370/161398428-95c05f87-6d6b-4669-9f30-7cb61664dab6.MOV

**Comment by jwflory** [comment]
Hi @bl-aire, this is a good start on research! 👍🏻 

I think we will not get the desired functionality using the built-in `aliases` or `url` in the front-matter. Instead, we can create our own front-matter parameters by creating a new layout. Looking back to the original issue, it is less important that the redirect appears on the home page as much as it is for a page to be redirected to an external site. This would also help solve a use case in unicef/inventory#128.

One way to do this is to create a new [single page template](https://gohugo.io/templates/single-page-templates/). This would be a layout used for a page, and when used, it could check for a `redirect-url` front-matter field. This could be a URL and then the HTML template could be a HTML and JavaScript redirect to that URL.

Does a single page template as a way to solve this make sense?

**Comment by bl-aire** [comment]
Hi @jwflory ,


> Hi @bl-aire, this is a good start on research! 👍🏻
> 
> I think we will not get the desired functionality using the built-in `aliases` or `url` in the front-matter. Instead, we can create our own front-matter parameters by creating a new layout. Looking back to the original issue, it is less important that the redirect appears on the home page as much as it is for a page to be redirected to an external site. This would also help solve a use case in [unicef/inventory#128](https://github.com/unicef/inventory/issues/128).
> 
> One way to do this is to create a new [single page template](https://gohugo.io/templates/single-page-templates/). This would be a layout used for a page, and when used, it could check for a `redirect-url` front-matter field. This could be a URL and then the HTML template could be a HTML and JavaScript redirect to that URL.
> 
> Does a single page template make sense as a way to solve this?

Using a single page template as a way to solve this does make sense. I will use this approach and give a progress report for review. Thanks for guiding me @jwflory

**Comment by jwflory** [comment]
No problem @bl-aire, please drop a line here if I can do anything to steer you the right way.

**Comment by bl-aire** [comment]
Hello @jwflory, while working on this issue I considered two options:

a. Having the user redirected to https://sdgs.un.org/goals immediately they click on the SDGS category in the navbar.

b. Opening the local sdgs page so a user is given a brief introduction about the Sustainable Development Goals before they are redirected automatically to the external link after a 10s delay.

![image](https://user-images.githubusercontent.com/84882370/162620340-ea68089c-b2d8-44ca-b5fd-be7b51f1fb35.jpeg)

I thought to try the second option because I believe it will create a better user-experience as users are introduced to what they should expect in the external link specified in the front matter.

I am open to reviews and suggestions on how I can make this better.

**Comment by jwflory** [comment]
@bl-aire Thanks for your patience with the feedback. 🙏🏻 I prefer not to do a redirect. I think that behavior is tricky and could have impact on search engine optimization depending how the redirect is handled (permanent, temporary, etc).

Although lately I was thinking that perhaps the approach outlined in the original comment is not right. I was thinking it could be interesting to create a new layout, or maybe an [archetype](https://gohugo.io/content-management/archetypes/), that handles the redirect. Just like some pages get declared as `type: docs`, this could be something like `type: redirect` together with a `url: https://example.com` field in a post's front-matter. This approach would solve the redirect challenge described above, as well as open up new possibilities for how we distribute and link out to third-party content.

**Comment by bl-aire** [comment]
Hello @jwflory, 
I really appreciate the feedback given.

I worked with it and was able to achieve the result needed. On clicking the SDGS subdirectory, the user gets redirected to an external URL. I achieved this by creating a custom archetype file which can be used subsequently.

**Comment by bl-aire** [comment]
> @bl-aire Thanks for your patience with the feedback. 🙏🏻 I prefer not to do a redirect. I think that behavior is tricky and could have impact on search engine optimization depending how the redirect is handled (permanent, temporary, etc).
> 
> 
> 
> Although lately I was thinking that perhaps the approach outlined in the original comment is not right. I was thinking it could be interesting to create a new layout, or maybe an [archetype](https://gohugo.io/content-management/archetypes/), that handles the redirect. Just like some pages get declared as `type: docs`, this could be something like `type: redirect` together with a `url: https://example.com` field in a post's front-matter. This approach would solve the redirect challenge described above, as well as open up new possibilities for how we distribute and link out to third-party content.


I achieved this but when I ran "Hugo serve --theme ../../" I got an error that read URL protocols with (http*) is not supported.

An alternative I tried was declaring the external url in the configuration file as SDGS's url and it worked but this would have to be hardcoded every time one has to link to a third party site in future and defeats the idea of creating a solution one can use in future.

Is there another solution to the error I can try?
