### ISSUE TITLE
Docs: Add table shortcode in Features category, Shortcodes page

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#71]
# Summary

Write new documentation to describe the table shortcode added in unicef/inventory-hugo-theme#70

# Background

This feature was added to support rendering complex information in tables as part of an exercise @acabunoc put together when working with Venture Fund companies. The feature should be documented in the sample website to better capture the capabilities and unique features of this theme from what comes natively with Hugo.

Note that the example site was not originally made to be a functioning form of documentation for the project, so some liberty will need to be taken in removing old content or repurposing it as we go.

# Details

The shortcode we use as found in [`/layouts/shortcodes/table.html`](https://github.com/unicef/inventory-hugo-theme/blob/main/layouts/shortcodes/table.html):

```go
{{ $_hugo_config := `{ "version": 1 }` }}

{{ $htmlTable := .Inner | markdownify }}
{{ $class := .Get 0 }}
{{ $old := "<table>" }}
{{ $new := printf "<table class=\"%s\">" $class }}
{{ $htmlTable := replace $htmlTable $old $new }}
{{ $htmlTable | safeHTML }}
```

The shortcode as it is used in a post from unicef/inventory#125:

```go
{{<table "table">}}

| Stakeholder | Role | Motivation | Open Source Work |
|----------|----------|----------|----------|
| < stakeholder 1 > ||||
| < stakeholder 2 > ||||
| < stakeholder 3 > ||||

{{</table>}}
```

Its actual appearance:

![Screenshot of the Stakeholder Mapping Exercise in the Open Source Inventory, which uses the table shortcode.](https://user-images.githubusercontent.com/4721034/158200399-1a91912c-4116-49ab-ac13-813b41ee5d07.png "Screenshot of the Stakeholder Mapping Exercise in the Open Source Inventory, which uses the table shortcode.")

# Outcome

Easier to discover this feature when using the theme

**Comment by yokwejuste** [comment]
> # Summary
> Write new documentation to describe the table shortcode added in #70
> 
> # Background
> This feature was added to support rendering complex information in tables as part of an exercise @acabunoc put together when working with Venture Fund companies. The feature should be documented in the sample website to better capture the capabilities and unique features of this theme from what comes natively with Hugo.
> 
> Note that the example site was not originally made to be a functioning form of documentation for the project, so some liberty will need to be taken in removing old content or repurposing it as we go.
> 
> # Details
> The shortcode we use as found in [`/layouts/shortcodes/table.html`](/layouts/shortcodes/table.html):
> 
> ```go
> {{ $_hugo_config := `{ "version": 1 }` }}
> 
> {{ $htmlTable := .Inner | markdownify }}
> {{ $class := .Get 0 }}
> {{ $old := "<table>" }}
> {{ $new := printf "<table class=\"%s\">" $class }}
> {{ $htmlTable := replace $htmlTable $old $new }}
> {{ $htmlTable | safeHTML }}
> ```
> 
> The shortcode as it is used in a post from [unicef/inventory#125](https://github.com/unicef/inventory/pull/125):
> 
> ```go
> {{<table "table">}}
> 
> | Stakeholder | Role | Motivation | Open Source Work |
> |----------|----------|----------|----------|
> | < stakeholder 1 > ||||
> | < stakeholder 2 > ||||
> | < stakeholder 3 > ||||
> 
> {{</table>}}
> ```
> 
> Its actual appearance:
> 
> ![Screenshot of the Stakeholder Mapping Exercise in the Open Source Inventory, which uses the table shortcode.](https://user-images.githubusercontent.com/4721034/158200399-1a91912c-4116-49ab-ac13-813b41ee5d07.png)
> 
> # Outcome
> Easier to discover this feature when using the theme

the link [/layouts/shortcodes/table.html](https://github.com/layouts/shortcodes/table.html) not working. The return is a 404.

**Comment by jwflory** [comment]
> the link [/layouts/shortcodes/table.html](https://github.com/layouts/shortcodes/table.html) not working. The return is a 404.

Thanks, I used a shortcut that doesn't seem to work with GitHub-flavored Markdown. I fixed the URL. It should have pointed here:

https://github.com/unicef/inventory-hugo-theme/blob/main/layouts/shortcodes/table.html

**Comment by BeeBombshell** [comment]
Hi @jwflory, I'm having a little trouble understanding what needs to be done. 😅 
The sample table on the [elements page](https://unicef.github.io/inventory-hugo-theme/installation/elements/) doesn't use the above-mentioned shortcode as of now. So, do we need to add a new table to document the shortcode or use it in an existing table?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/53828745/161395727-277a3d3c-8a4f-4a12-aaf1-3bc374d55189.png">

Also, the shortcode table looks exactly the same as the normal HTML table. Even the styling done for the `table` element will affect both the normal HTML table and the shortcode table. So, I don't understand how a user will differentiate between the two.

**Comment by jwflory** [comment]
> The sample table on the [elements page](https://unicef.github.io/inventory-hugo-theme/installation/elements/) doesn't use the above-mentioned shortcode as of now. So, do we need to add a new table to document the shortcode or use it in an existing table?

The documentation site should use the table shortcode instead of the Markdown table. This is because the shortcode works across both Markdown and Asciidoc content.

> Also, the shortcode table looks exactly the same as the normal HTML table. Even the styling done for the `table` element will affect both the normal HTML table and the shortcode table. So, I don't understand how a user will differentiate between the two.

This is the documentation for content writers and not for readers/users. A content writer should use the shortcode when creating tables. A reader or user should not know the difference. So, the fix here is very simple! It is padding the existing Markdown table with the shortcode and perhaps adding a link to a [Markdown table generator tool](https://www.tablesgenerator.com/markdown_tables) or other Markdown documentation.

Does it make sense?

**Comment by BeeBombshell** [comment]
@jwflory Yes, makes sense to me... 😊

Can I work on this issue?

**Comment by jwflory** [comment]
@BeeBombshell Definitely! 👍🏻
