### ISSUE TITLE
https://github.com/unicef/inventory-hugo-theme/blob/main/sample_config.yaml

### ISSUE THREAD

**Issue by yokwejuste** [unicef/inventory-hugo-theme#79]
# Summary
On clicking on the [sample config](https://github.com/unicef/inventory-hugo-theme/blob/main/sample_config.yaml) link found out not to be existing.

# Background
I think you should solve it! Not nice leaving it that war

**Comment by Neha9849** [comment]
I think we should replace the above link in the Readme file with this https://github.com/unicef/inventory-hugo-theme/blob/main/exampleSite/config.yaml 
@Idadelveloper what do you think?

**Comment by jwflory** [comment]
@yokwejuste Thanks for pointing this out. I fixed where it is mentioned in PR #82, as pointed out by @Neha9849.
