### ISSUE TITLE
📝 🖊️Minor change to the mobile view

### ISSUE THREAD

**Issue by yokwejuste** [unicef/inventory-hugo-theme#87]
# Summary
On trying the mobile view, noticed the navbar drop-down icon [☰](#) remains unchanged. Suggested that a feature like this should be brought to it as seen below.
![on-click-x](https://codemyui.com/wp-content/uploads/2017/03/menu-button.gif)
The feature looks cool and pretty nice.
# Background
As for now, the effect looks like this:
![on-click effect](https://user-images.githubusercontent.com/71908316/161027433-387cf3d5-c957-415c-8409-14a99880ed3a.gif)
From the UX point of view, a dropdown menu will be more attractive if effects and interactions are added to it. 

**Describe any alternatives considered**:
Alternatively, you can stick to what is already there. Or assign this issue to me! so that I can work on the implementation of an appropriate solution for this.
# Details
The implementation of this is simple and direct and can consist of either javascript or CSS. To make it faster and more interactive, javascript suits best for this. 
- With CSS using the : before and :aftereffects will clearly be done.
- Concerning JS, with onclick="statement", the task is perfectly done too.

# Outcome
The only impact of this effect is beautifying the UI  and improve the user experience-UX

**Comment by jwflory** [comment]
@yokwejuste Seems like an interesting idea. It can be a small step towards improving the mobile experience. You can go ahead and take on this one, but make sure you first complete your ongoing work for #78 in PR #81.

**Comment by yokwejuste** [comment]
@jwflory concerning #78 and #81 I just made some updates today! you can check them.

**Comment by yokwejuste** [comment]
@jwflory concerning #78 and #81 I just made some updates today! you can check them.

**Comment by Hydriah** [comment]
hello@jwflory  please i don't know if @yokwejuste  has started working on this since he has an ongoing task so i can go it

**Comment by yokwejuste** [comment]
Hey @jwflory ! Some improvements made from this [PR](https://github.com/unicef/inventory-hugo-theme/pull/81).

**Comment by yokwejuste** [comment]
> Hey @jwflory ! Some improvements made from this [PR](https://github.com/unicef/inventory-hugo-theme/pull/81) ![thegif](https://user-images.githubusercontent.com/71908316/162553434-f2221c63-5ca1-4c75-bd51-6bc98e8085d1.gif)

Can i move ahead with another contribution since this issue has being solved! @jwflory ?

**Comment by jwflory** [comment]
Hi, I'm sorry for the late follow-up. We'll continue to track this issue on PR #81.

**Comment by jwflory** [comment]
We reached the end of Sprint 2 today. The feedback from this issue will be tracked in #122 and #125. Closing as `duplicate`.
