### ISSUE TITLE
Improve the UI by highlighting buttons on hovering

### ISSUE THREAD

**Issue by AbihaFatima** [unicef/inventory-hugo-theme#90]
# Summary

Highlight the background color of buttons while hovering.

# Background

**Is the improvement related to a problem? Describe the problem**:
The `CONTACT US` button [here](https://unicef.github.io/inventory-hugo-theme/) and `SEND` button [here](https://unicef.github.io/inventory-hugo-theme/contact/) should highlight the background color while hovering, as this helps to spot the button is about to be selected or clicked. This change can improve the UI of the website.

**What does the improvement look like to you?**:
It should look something like this: 
![bg-color-change-2](https://user-images.githubusercontent.com/70844041/161323798-2a8fc6a7-ce47-455a-8ccc-85afeedd54af.gif)
For now I modified it using my browser’s DevTools.

**Describe any alternatives considered**:
The background color after hovering could either be turned to gray or the ligher shade of already existing primary-color (the one used above).

# Details

This could be implemented by adding the color in [styles.css](https://github.com/unicef/inventory-hugo-theme/blob/main/assets/css/style.css).

# Outcome

The key outcome of the above scenario is that the background color of button under the hover will be slightly lighter than the primary color of the button to simply let users know that it is clickable in addition to the cursor change.

**Comment by AbihaFatima** [comment]
@jwflory @Idadelveloper 
If approved, I would like to work on this :)

**Comment by jwflory** [comment]
@AbihaFatima Thanks for your patience! Yes, I agree that this would be an improvement. It was something I noticed missing a while back. Feel free to start on this.

**Comment by jwflory** [comment]
Thanks for working on this one @AbihaFatima!
