### ISSUE TITLE
🌹 Adding french content.

### ISSUE THREAD

**Issue by yokwejuste** [unicef/inventory-hugo-theme#93]
# Summary
After I went through the [UNICEF inventory theme website](https://unicef.github.io/inventory-hugo-theme/fr/installation/) something hooked me up, and I realized the french page was not appropriate. I mean not been translated into french yet.
![image](https://user-images.githubusercontent.com/71908316/161467834-0083242d-7988-4fbf-a08f-4728e1075a04.png)
![image](https://user-images.githubusercontent.com/71908316/161467974-a68556e5-ece9-429b-87d5-3208a763dbba.png)
As seen above, all the content is still in English but it's funny knowing this is the french version of the site.

# Background
UNICEF as a diverse organisation, not promoting discrimination should endeavour to bring the whole users population to work or go through their website. French and more can be added but what brings up this issue is the french language.

**Is the new feature related to a problem? Describe the problem**:
The feature is not that new just some small improvement that is needed here.

**What does the new feature look like to you?**:
The feature will just be the content in french. The picture says enough than I do now.
![image](https://user-images.githubusercontent.com/71908316/161468286-5a7e39cc-db1a-4f79-95df-ea06710aceff.png)

**Describe any alternatives considered**:
Alternatively, a google translate extension can be used to perform the task.

# Outcome
The outcome will include diversity and better user access together improving the user experience on-site.

**Comment by jwflory** [comment]
Hi @yokwejuste, better localization is a great point and something that would make the theme more inclusive for others to use.

I'd like to hold off on localization work until #89 moves forward. I see the example site taking on a new form and function in the coming months, and it would be a shame to localize the existing content, for it to change later on. Also, it would be a good time to look at how localization is done currently and how that could be improved across the theme as a whole.

I'll keep this one open, but I'm marking it as blocked (for now) until the content reorganization work takes place.

**Comment by jwflory** [comment]
The content reorganization work is taking place in #148, #149, and #118. The example site content was changed from French to Spanish (see commit c3ae5ab7c4957f30734ae7c53850ee3a6452c998 in PR #148). Given the ongoing work with localizations, I am closing this issue as `duplicate`.
