### ISSUE TITLE
Improve the UI of the Inventory Cards in the Explore Section.

### ISSUE THREAD

**Issue by EmmanuelOloke** [unicef/inventory-hugo-theme#97]
# Summary

Improve the UI of the inventory card explore section by adding border-radius, box-shadows and subtle transition to individual cards 

# Background

The current design looks quite basic and does not conform to the modern UI look of a professional website. With the improvements I plan to make, the inventory page will look a lot better and more pleasing to users. Adding box-shadow, border-radius and hover state transitions to the cards with take the page from basic to professional.

**Is the improvement related to a problem? Describe the problem**: I believe the problem we're trying to solve in this contribution phase is to generally improve the whole UI/UX of the Unicef inventory website and I think the improvement I've proposed is a step in that direction

**What does the improvement look like to you?**: I will take design inspiration and cues from the official UNICEF website (www.unicef.org) homepage for Product Uniformity. So users already used to the UI/UX of the main Unicef website will feel familiar with the inventory which is important for User Experience.

**Describe any alternatives considered**: I will try to improve the current state with the use of base Bootstrap classes and design. But If that cannot give the result I envision, an alternative will be to write custom CSS in order to achieve desired results.

# Details

This will be a straightforward implementation as I only want to make changes to the HTML and CSS files related to the inventory homepage but I will like for the mentor to further enlighten me about the best way they prefer prospective interns to make contributions. So I do not write an implementation that will be unsatisfactory to the mentor and probably break another functionality in other parts of the project.

# Outcome

At the end of this contribution, the overall UI/UX of the project will be much improved which takes us closer to the final goal of improving the entire project's User Interface and User Experience. I look forward to completing this issue if given the opportunity and also making more contributions in the future.

The current state of the inventory cards
<img width="1213" alt="Screenshot 2022-04-11 at 17 49 35" src="https://user-images.githubusercontent.com/16335826/162790496-047baa65-28fe-406a-b390-9dd3d0c8145b.png">

What I intend to achieve on completion of this issue will look similar to this.
<img width="1420" alt="Screenshot 2022-04-11 at 17 51 41" src="https://user-images.githubusercontent.com/16335826/162790780-4047261c-e67c-4ac3-8242-7c5201f948ab.png">

Please kindly respond, @Idadelveloper @jwflory

**Comment by Idadelveloper** [comment]
@EmmanuelOloke do you plan on adding images to the cards?

**Comment by EmmanuelOloke** [comment]
No I do not... I just shared this particular image to showcase the box-shadow and border-radius and what it will look like when done

**Comment by Idadelveloper** [comment]
@jwflory what are your thoughts?

**Comment by EmmanuelOloke** [comment]
@Idadelveloper @jwflory Also, please I'll like some pointers on which directory the HTML and CSS files are located, and how best to go about making these changes. It's been quite challenging trying to figure my way around the theme/framework and I'll really appreciate the help. Thanks.

**Comment by Idadelveloper** [comment]
@EmmanuelOloke the CSS is located in `assets/css/style.css`. Also bear in mind we utilized some bootstrap. The HTML is in the `layouts` directory. Go through the Hugo docs again and it will all make sense.

**Comment by EmmanuelOloke** [comment]
Alright... I see now... I still have some questions please, as I'm still a little confused about the workflow. After completing the onboarding tasks, I can only run "hugo-serve" in the directory of task 2 and not task 3 which is where I have a cloned branch of the repo. When I run "hugo-serve" in the cloned branch directory I get "unable to locate config file or config directory" error, is that how it's supposed to work or there's something I'm missing.

Also, must I pull in the latest version of the main repo to see the current state of the project and the changes already made, so I don't end up working on changes someone else has already implemented.

I'm new to open source contribution so I hope these questions are not an inconvenience to you, I will really like to make impactful contributions to this project and I really need help to do that. Thanks

**Comment by EmmanuelOloke** [comment]
@Idadelveloper I'm still waiting on a reply to this please, any help I can get will be really great, thanks.

**Comment by jwflory** [comment]
Hi @EmmanuelOloke, thanks for your feedback and suggestion. I appreciate your patience. These are changes we can incorporate into the theme. I am adding this issue to our sprint board.

**Comment by jwflory** [comment]
Hi @EmmanuelOloke, are you still interested in contributing the improvements detailed in this issue? If not, I can open it up for someone else in the community to work on.

**Comment by EmmanuelOloke** [comment]
Hello @jwflory, Good day, thanks for reaching out and giving the opportunity to continue working on the project. Sadly, I've become involved in other engagements and will not be able to continue contributing at this time. I look forward to contributing to Outreachy projects in the future and wish the entire community well. Thanks for all the help and lesson learnt.

**Comment by jwflory** [comment]
Fixed by #117.
